// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BattleRecord.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Battle.Record {

  /// <summary>Holder for reflection information generated from BattleRecord.proto</summary>
  public static partial class BattleRecordReflection {

    #region Descriptor
    /// <summary>File descriptor for BattleRecord.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleRecordReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJCYXR0bGVSZWNvcmQucHJvdG8SF01ldGFWaXJ1cy5iYXR0bGUucmVjb3Jk",
            "GhRCYXR0bGVVbml0RGF0YS5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5w",
            "cm90byKrAgoOQmF0dGxlUmVjb3JkUGISEAoIYmF0dGxlSWQYASABKAUSFAoM",
            "dGlja0ludGVydmFsGAIgASgFEjsKCHNyY1VuaXRzGAMgAygLMikuTWV0YVZp",
            "cnVzLmJhdHRsZS5yZWNvcmQuQmF0dGxlVW5pdERhdGFQYhI7Cgh0YXJVbml0",
            "cxgEIAMoCzIpLk1ldGFWaXJ1cy5iYXR0bGUucmVjb3JkLkJhdHRsZVVuaXRE",
            "YXRhUGISJAoGZnJhbWVzGAUgAygLMhQuZ29vZ2xlLnByb3RvYnVmLkFueRIZ",
            "ChFyb3VuZEFjdGlvbkVuZXJneRgGIAEoBRIPCgdzcmNOYW1lGAcgASgJEg8K",
            "B3Rhck5hbWUYCCABKAkSFAoMYmF0dGxlUmVzdWx0GAkgASgFQjIKG2NvbS5t",
            "ZXRhdmlydXMuYmF0dGxlLnJlY29yZEIRQmF0dGxlUmVjb3JkUEJPdXRQAWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MetaVirus.Battle.Record.BattleUnitDataReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Battle.Record.BattleRecordPb), global::MetaVirus.Battle.Record.BattleRecordPb.Parser, new[]{ "BattleId", "TickInterval", "SrcUnits", "TarUnits", "Frames", "RoundActionEnergy", "SrcName", "TarName", "BattleResult" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BattleRecordPb : pb::IMessage<BattleRecordPb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BattleRecordPb> _parser = new pb::MessageParser<BattleRecordPb>(() => new BattleRecordPb());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BattleRecordPb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Battle.Record.BattleRecordReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRecordPb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRecordPb(BattleRecordPb other) : this() {
      battleId_ = other.battleId_;
      tickInterval_ = other.tickInterval_;
      srcUnits_ = other.srcUnits_.Clone();
      tarUnits_ = other.tarUnits_.Clone();
      frames_ = other.frames_.Clone();
      roundActionEnergy_ = other.roundActionEnergy_;
      srcName_ = other.srcName_;
      tarName_ = other.tarName_;
      battleResult_ = other.battleResult_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRecordPb Clone() {
      return new BattleRecordPb(this);
    }

    /// <summary>Field number for the "battleId" field.</summary>
    public const int BattleIdFieldNumber = 1;
    private int battleId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BattleId {
      get { return battleId_; }
      set {
        battleId_ = value;
      }
    }

    /// <summary>Field number for the "tickInterval" field.</summary>
    public const int TickIntervalFieldNumber = 2;
    private int tickInterval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TickInterval {
      get { return tickInterval_; }
      set {
        tickInterval_ = value;
      }
    }

    /// <summary>Field number for the "srcUnits" field.</summary>
    public const int SrcUnitsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::MetaVirus.Battle.Record.BattleUnitDataPb> _repeated_srcUnits_codec
        = pb::FieldCodec.ForMessage(26, global::MetaVirus.Battle.Record.BattleUnitDataPb.Parser);
    private readonly pbc::RepeatedField<global::MetaVirus.Battle.Record.BattleUnitDataPb> srcUnits_ = new pbc::RepeatedField<global::MetaVirus.Battle.Record.BattleUnitDataPb>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MetaVirus.Battle.Record.BattleUnitDataPb> SrcUnits {
      get { return srcUnits_; }
    }

    /// <summary>Field number for the "tarUnits" field.</summary>
    public const int TarUnitsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::MetaVirus.Battle.Record.BattleUnitDataPb> _repeated_tarUnits_codec
        = pb::FieldCodec.ForMessage(34, global::MetaVirus.Battle.Record.BattleUnitDataPb.Parser);
    private readonly pbc::RepeatedField<global::MetaVirus.Battle.Record.BattleUnitDataPb> tarUnits_ = new pbc::RepeatedField<global::MetaVirus.Battle.Record.BattleUnitDataPb>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MetaVirus.Battle.Record.BattleUnitDataPb> TarUnits {
      get { return tarUnits_; }
    }

    /// <summary>Field number for the "frames" field.</summary>
    public const int FramesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Any> _repeated_frames_codec
        = pb::FieldCodec.ForMessage(42, global::Google.Protobuf.WellKnownTypes.Any.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> frames_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> Frames {
      get { return frames_; }
    }

    /// <summary>Field number for the "roundActionEnergy" field.</summary>
    public const int RoundActionEnergyFieldNumber = 6;
    private int roundActionEnergy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoundActionEnergy {
      get { return roundActionEnergy_; }
      set {
        roundActionEnergy_ = value;
      }
    }

    /// <summary>Field number for the "srcName" field.</summary>
    public const int SrcNameFieldNumber = 7;
    private string srcName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SrcName {
      get { return srcName_; }
      set {
        srcName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tarName" field.</summary>
    public const int TarNameFieldNumber = 8;
    private string tarName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TarName {
      get { return tarName_; }
      set {
        tarName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "battleResult" field.</summary>
    public const int BattleResultFieldNumber = 9;
    private int battleResult_;
    /// <summary>
    ///战斗结果 0胜 1平 2负
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BattleResult {
      get { return battleResult_; }
      set {
        battleResult_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BattleRecordPb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BattleRecordPb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BattleId != other.BattleId) return false;
      if (TickInterval != other.TickInterval) return false;
      if(!srcUnits_.Equals(other.srcUnits_)) return false;
      if(!tarUnits_.Equals(other.tarUnits_)) return false;
      if(!frames_.Equals(other.frames_)) return false;
      if (RoundActionEnergy != other.RoundActionEnergy) return false;
      if (SrcName != other.SrcName) return false;
      if (TarName != other.TarName) return false;
      if (BattleResult != other.BattleResult) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BattleId != 0) hash ^= BattleId.GetHashCode();
      if (TickInterval != 0) hash ^= TickInterval.GetHashCode();
      hash ^= srcUnits_.GetHashCode();
      hash ^= tarUnits_.GetHashCode();
      hash ^= frames_.GetHashCode();
      if (RoundActionEnergy != 0) hash ^= RoundActionEnergy.GetHashCode();
      if (SrcName.Length != 0) hash ^= SrcName.GetHashCode();
      if (TarName.Length != 0) hash ^= TarName.GetHashCode();
      if (BattleResult != 0) hash ^= BattleResult.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BattleId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BattleId);
      }
      if (TickInterval != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TickInterval);
      }
      srcUnits_.WriteTo(output, _repeated_srcUnits_codec);
      tarUnits_.WriteTo(output, _repeated_tarUnits_codec);
      frames_.WriteTo(output, _repeated_frames_codec);
      if (RoundActionEnergy != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(RoundActionEnergy);
      }
      if (SrcName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SrcName);
      }
      if (TarName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(TarName);
      }
      if (BattleResult != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(BattleResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BattleId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BattleId);
      }
      if (TickInterval != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TickInterval);
      }
      srcUnits_.WriteTo(ref output, _repeated_srcUnits_codec);
      tarUnits_.WriteTo(ref output, _repeated_tarUnits_codec);
      frames_.WriteTo(ref output, _repeated_frames_codec);
      if (RoundActionEnergy != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(RoundActionEnergy);
      }
      if (SrcName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SrcName);
      }
      if (TarName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(TarName);
      }
      if (BattleResult != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(BattleResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BattleId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BattleId);
      }
      if (TickInterval != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TickInterval);
      }
      size += srcUnits_.CalculateSize(_repeated_srcUnits_codec);
      size += tarUnits_.CalculateSize(_repeated_tarUnits_codec);
      size += frames_.CalculateSize(_repeated_frames_codec);
      if (RoundActionEnergy != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoundActionEnergy);
      }
      if (SrcName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SrcName);
      }
      if (TarName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TarName);
      }
      if (BattleResult != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BattleResult);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BattleRecordPb other) {
      if (other == null) {
        return;
      }
      if (other.BattleId != 0) {
        BattleId = other.BattleId;
      }
      if (other.TickInterval != 0) {
        TickInterval = other.TickInterval;
      }
      srcUnits_.Add(other.srcUnits_);
      tarUnits_.Add(other.tarUnits_);
      frames_.Add(other.frames_);
      if (other.RoundActionEnergy != 0) {
        RoundActionEnergy = other.RoundActionEnergy;
      }
      if (other.SrcName.Length != 0) {
        SrcName = other.SrcName;
      }
      if (other.TarName.Length != 0) {
        TarName = other.TarName;
      }
      if (other.BattleResult != 0) {
        BattleResult = other.BattleResult;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BattleId = input.ReadInt32();
            break;
          }
          case 16: {
            TickInterval = input.ReadInt32();
            break;
          }
          case 26: {
            srcUnits_.AddEntriesFrom(input, _repeated_srcUnits_codec);
            break;
          }
          case 34: {
            tarUnits_.AddEntriesFrom(input, _repeated_tarUnits_codec);
            break;
          }
          case 42: {
            frames_.AddEntriesFrom(input, _repeated_frames_codec);
            break;
          }
          case 48: {
            RoundActionEnergy = input.ReadInt32();
            break;
          }
          case 58: {
            SrcName = input.ReadString();
            break;
          }
          case 66: {
            TarName = input.ReadString();
            break;
          }
          case 72: {
            BattleResult = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BattleId = input.ReadInt32();
            break;
          }
          case 16: {
            TickInterval = input.ReadInt32();
            break;
          }
          case 26: {
            srcUnits_.AddEntriesFrom(ref input, _repeated_srcUnits_codec);
            break;
          }
          case 34: {
            tarUnits_.AddEntriesFrom(ref input, _repeated_tarUnits_codec);
            break;
          }
          case 42: {
            frames_.AddEntriesFrom(ref input, _repeated_frames_codec);
            break;
          }
          case 48: {
            RoundActionEnergy = input.ReadInt32();
            break;
          }
          case 58: {
            SrcName = input.ReadString();
            break;
          }
          case 66: {
            TarName = input.ReadString();
            break;
          }
          case 72: {
            BattleResult = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
