// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BuffActionFrame.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Battle.Record {

  /// <summary>Holder for reflection information generated from BuffActionFrame.proto</summary>
  public static partial class BuffActionFrameReflection {

    #region Descriptor
    /// <summary>File descriptor for BuffActionFrame.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BuffActionFrameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVCdWZmQWN0aW9uRnJhbWUucHJvdG8SF01ldGFWaXJ1cy5iYXR0bGUucmVj",
            "b3JkIt8BChFCdWZmQWN0aW9uRnJhbWVQYhIRCglmcmFtZVR5cGUYASABKAUS",
            "EQoJZnJhbWVUaW1lGAIgASgFEg4KBmJ1ZmZJZBgDIAEoBRISCgpidWZmRGF0",
            "YUlkGAQgASgFEhAKCHRhcmdldElkGAUgASgFEhYKDmJ1ZmZBY3Rpb25UeXBl",
            "GAYgASgFEhEKCXJlbWFpbmluZxgHIAEoBRIXCg9lZmZlY3RBdHRyaWJ1dGUY",
            "CCABKAUSEwoLZWZmZWN0VmFsdWUYCSABKAUSFQoNcmVzdWx0VG9EZWF0aBgK",
            "IAEoCEI1Chtjb20ubWV0YXZpcnVzLmJhdHRsZS5yZWNvcmRCFEJ1ZmZBY3Rp",
            "b25GcmFtZVBCT3V0UAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Battle.Record.BuffActionFramePb), global::MetaVirus.Battle.Record.BuffActionFramePb.Parser, new[]{ "FrameType", "FrameTime", "BuffId", "BuffDataId", "TargetId", "BuffActionType", "Remaining", "EffectAttribute", "EffectValue", "ResultToDeath" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BuffActionFramePb : pb::IMessage<BuffActionFramePb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BuffActionFramePb> _parser = new pb::MessageParser<BuffActionFramePb>(() => new BuffActionFramePb());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BuffActionFramePb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Battle.Record.BuffActionFrameReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuffActionFramePb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuffActionFramePb(BuffActionFramePb other) : this() {
      frameType_ = other.frameType_;
      frameTime_ = other.frameTime_;
      buffId_ = other.buffId_;
      buffDataId_ = other.buffDataId_;
      targetId_ = other.targetId_;
      buffActionType_ = other.buffActionType_;
      remaining_ = other.remaining_;
      effectAttribute_ = other.effectAttribute_;
      effectValue_ = other.effectValue_;
      resultToDeath_ = other.resultToDeath_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuffActionFramePb Clone() {
      return new BuffActionFramePb(this);
    }

    /// <summary>Field number for the "frameType" field.</summary>
    public const int FrameTypeFieldNumber = 1;
    private int frameType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FrameType {
      get { return frameType_; }
      set {
        frameType_ = value;
      }
    }

    /// <summary>Field number for the "frameTime" field.</summary>
    public const int FrameTimeFieldNumber = 2;
    private int frameTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FrameTime {
      get { return frameTime_; }
      set {
        frameTime_ = value;
      }
    }

    /// <summary>Field number for the "buffId" field.</summary>
    public const int BuffIdFieldNumber = 3;
    private int buffId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BuffId {
      get { return buffId_; }
      set {
        buffId_ = value;
      }
    }

    /// <summary>Field number for the "buffDataId" field.</summary>
    public const int BuffDataIdFieldNumber = 4;
    private int buffDataId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BuffDataId {
      get { return buffDataId_; }
      set {
        buffDataId_ = value;
      }
    }

    /// <summary>Field number for the "targetId" field.</summary>
    public const int TargetIdFieldNumber = 5;
    private int targetId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "buffActionType" field.</summary>
    public const int BuffActionTypeFieldNumber = 6;
    private int buffActionType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BuffActionType {
      get { return buffActionType_; }
      set {
        buffActionType_ = value;
      }
    }

    /// <summary>Field number for the "remaining" field.</summary>
    public const int RemainingFieldNumber = 7;
    private int remaining_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Remaining {
      get { return remaining_; }
      set {
        remaining_ = value;
      }
    }

    /// <summary>Field number for the "effectAttribute" field.</summary>
    public const int EffectAttributeFieldNumber = 8;
    private int effectAttribute_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EffectAttribute {
      get { return effectAttribute_; }
      set {
        effectAttribute_ = value;
      }
    }

    /// <summary>Field number for the "effectValue" field.</summary>
    public const int EffectValueFieldNumber = 9;
    private int effectValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EffectValue {
      get { return effectValue_; }
      set {
        effectValue_ = value;
      }
    }

    /// <summary>Field number for the "resultToDeath" field.</summary>
    public const int ResultToDeathFieldNumber = 10;
    private bool resultToDeath_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ResultToDeath {
      get { return resultToDeath_; }
      set {
        resultToDeath_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BuffActionFramePb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BuffActionFramePb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FrameType != other.FrameType) return false;
      if (FrameTime != other.FrameTime) return false;
      if (BuffId != other.BuffId) return false;
      if (BuffDataId != other.BuffDataId) return false;
      if (TargetId != other.TargetId) return false;
      if (BuffActionType != other.BuffActionType) return false;
      if (Remaining != other.Remaining) return false;
      if (EffectAttribute != other.EffectAttribute) return false;
      if (EffectValue != other.EffectValue) return false;
      if (ResultToDeath != other.ResultToDeath) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FrameType != 0) hash ^= FrameType.GetHashCode();
      if (FrameTime != 0) hash ^= FrameTime.GetHashCode();
      if (BuffId != 0) hash ^= BuffId.GetHashCode();
      if (BuffDataId != 0) hash ^= BuffDataId.GetHashCode();
      if (TargetId != 0) hash ^= TargetId.GetHashCode();
      if (BuffActionType != 0) hash ^= BuffActionType.GetHashCode();
      if (Remaining != 0) hash ^= Remaining.GetHashCode();
      if (EffectAttribute != 0) hash ^= EffectAttribute.GetHashCode();
      if (EffectValue != 0) hash ^= EffectValue.GetHashCode();
      if (ResultToDeath != false) hash ^= ResultToDeath.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrameType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FrameType);
      }
      if (FrameTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FrameTime);
      }
      if (BuffId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BuffId);
      }
      if (BuffDataId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(BuffDataId);
      }
      if (TargetId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(TargetId);
      }
      if (BuffActionType != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(BuffActionType);
      }
      if (Remaining != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Remaining);
      }
      if (EffectAttribute != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(EffectAttribute);
      }
      if (EffectValue != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(EffectValue);
      }
      if (ResultToDeath != false) {
        output.WriteRawTag(80);
        output.WriteBool(ResultToDeath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrameType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FrameType);
      }
      if (FrameTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FrameTime);
      }
      if (BuffId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BuffId);
      }
      if (BuffDataId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(BuffDataId);
      }
      if (TargetId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(TargetId);
      }
      if (BuffActionType != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(BuffActionType);
      }
      if (Remaining != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Remaining);
      }
      if (EffectAttribute != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(EffectAttribute);
      }
      if (EffectValue != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(EffectValue);
      }
      if (ResultToDeath != false) {
        output.WriteRawTag(80);
        output.WriteBool(ResultToDeath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FrameType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrameType);
      }
      if (FrameTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrameTime);
      }
      if (BuffId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuffId);
      }
      if (BuffDataId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuffDataId);
      }
      if (TargetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetId);
      }
      if (BuffActionType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuffActionType);
      }
      if (Remaining != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Remaining);
      }
      if (EffectAttribute != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EffectAttribute);
      }
      if (EffectValue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EffectValue);
      }
      if (ResultToDeath != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BuffActionFramePb other) {
      if (other == null) {
        return;
      }
      if (other.FrameType != 0) {
        FrameType = other.FrameType;
      }
      if (other.FrameTime != 0) {
        FrameTime = other.FrameTime;
      }
      if (other.BuffId != 0) {
        BuffId = other.BuffId;
      }
      if (other.BuffDataId != 0) {
        BuffDataId = other.BuffDataId;
      }
      if (other.TargetId != 0) {
        TargetId = other.TargetId;
      }
      if (other.BuffActionType != 0) {
        BuffActionType = other.BuffActionType;
      }
      if (other.Remaining != 0) {
        Remaining = other.Remaining;
      }
      if (other.EffectAttribute != 0) {
        EffectAttribute = other.EffectAttribute;
      }
      if (other.EffectValue != 0) {
        EffectValue = other.EffectValue;
      }
      if (other.ResultToDeath != false) {
        ResultToDeath = other.ResultToDeath;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FrameType = input.ReadInt32();
            break;
          }
          case 16: {
            FrameTime = input.ReadInt32();
            break;
          }
          case 24: {
            BuffId = input.ReadInt32();
            break;
          }
          case 32: {
            BuffDataId = input.ReadInt32();
            break;
          }
          case 40: {
            TargetId = input.ReadInt32();
            break;
          }
          case 48: {
            BuffActionType = input.ReadInt32();
            break;
          }
          case 56: {
            Remaining = input.ReadInt32();
            break;
          }
          case 64: {
            EffectAttribute = input.ReadInt32();
            break;
          }
          case 72: {
            EffectValue = input.ReadInt32();
            break;
          }
          case 80: {
            ResultToDeath = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FrameType = input.ReadInt32();
            break;
          }
          case 16: {
            FrameTime = input.ReadInt32();
            break;
          }
          case 24: {
            BuffId = input.ReadInt32();
            break;
          }
          case 32: {
            BuffDataId = input.ReadInt32();
            break;
          }
          case 40: {
            TargetId = input.ReadInt32();
            break;
          }
          case 48: {
            BuffActionType = input.ReadInt32();
            break;
          }
          case 56: {
            Remaining = input.ReadInt32();
            break;
          }
          case 64: {
            EffectAttribute = input.ReadInt32();
            break;
          }
          case 72: {
            EffectValue = input.ReadInt32();
            break;
          }
          case 80: {
            ResultToDeath = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
