// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FrameSkillCastData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Battle.Record {

  /// <summary>Holder for reflection information generated from FrameSkillCastData.proto</summary>
  public static partial class FrameSkillCastDataReflection {

    #region Descriptor
    /// <summary>File descriptor for FrameSkillCastData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FrameSkillCastDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhGcmFtZVNraWxsQ2FzdERhdGEucHJvdG8SF01ldGFWaXJ1cy5iYXR0bGUu",
            "cmVjb3JkGhRCdWZmQXR0YWNoRGF0YS5wcm90bxoTU2tpbGxDYXN0RGF0YS5w",
            "cm90byLTAQoURnJhbWVTa2lsbENhc3REYXRhUGISOgoIY2FzdERhdGEYASAB",
            "KAsyKC5NZXRhVmlydXMuYmF0dGxlLnJlY29yZC5Ta2lsbENhc3REYXRhUGIS",
            "PwoNYXR0YWNoRWZmZWN0cxgCIAMoCzIoLk1ldGFWaXJ1cy5iYXR0bGUucmVj",
            "b3JkLlNraWxsQ2FzdERhdGFQYhI+CgthdHRhY2hCdWZmcxgDIAMoCzIpLk1l",
            "dGFWaXJ1cy5iYXR0bGUucmVjb3JkLkJ1ZmZBdHRhY2hEYXRhUGJCOAobY29t",
            "Lm1ldGF2aXJ1cy5iYXR0bGUucmVjb3JkQhdGcmFtZVNraWxsQ2FzdERhdGFQ",
            "Qk91dFABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MetaVirus.Battle.Record.BuffAttachDataReflection.Descriptor, global::MetaVirus.Battle.Record.SkillCastDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Battle.Record.FrameSkillCastDataPb), global::MetaVirus.Battle.Record.FrameSkillCastDataPb.Parser, new[]{ "CastData", "AttachEffects", "AttachBuffs" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FrameSkillCastDataPb : pb::IMessage<FrameSkillCastDataPb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FrameSkillCastDataPb> _parser = new pb::MessageParser<FrameSkillCastDataPb>(() => new FrameSkillCastDataPb());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FrameSkillCastDataPb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Battle.Record.FrameSkillCastDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameSkillCastDataPb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameSkillCastDataPb(FrameSkillCastDataPb other) : this() {
      castData_ = other.castData_ != null ? other.castData_.Clone() : null;
      attachEffects_ = other.attachEffects_.Clone();
      attachBuffs_ = other.attachBuffs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameSkillCastDataPb Clone() {
      return new FrameSkillCastDataPb(this);
    }

    /// <summary>Field number for the "castData" field.</summary>
    public const int CastDataFieldNumber = 1;
    private global::MetaVirus.Battle.Record.SkillCastDataPb castData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MetaVirus.Battle.Record.SkillCastDataPb CastData {
      get { return castData_; }
      set {
        castData_ = value;
      }
    }

    /// <summary>Field number for the "attachEffects" field.</summary>
    public const int AttachEffectsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::MetaVirus.Battle.Record.SkillCastDataPb> _repeated_attachEffects_codec
        = pb::FieldCodec.ForMessage(18, global::MetaVirus.Battle.Record.SkillCastDataPb.Parser);
    private readonly pbc::RepeatedField<global::MetaVirus.Battle.Record.SkillCastDataPb> attachEffects_ = new pbc::RepeatedField<global::MetaVirus.Battle.Record.SkillCastDataPb>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MetaVirus.Battle.Record.SkillCastDataPb> AttachEffects {
      get { return attachEffects_; }
    }

    /// <summary>Field number for the "attachBuffs" field.</summary>
    public const int AttachBuffsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::MetaVirus.Battle.Record.BuffAttachDataPb> _repeated_attachBuffs_codec
        = pb::FieldCodec.ForMessage(26, global::MetaVirus.Battle.Record.BuffAttachDataPb.Parser);
    private readonly pbc::RepeatedField<global::MetaVirus.Battle.Record.BuffAttachDataPb> attachBuffs_ = new pbc::RepeatedField<global::MetaVirus.Battle.Record.BuffAttachDataPb>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MetaVirus.Battle.Record.BuffAttachDataPb> AttachBuffs {
      get { return attachBuffs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FrameSkillCastDataPb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FrameSkillCastDataPb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CastData, other.CastData)) return false;
      if(!attachEffects_.Equals(other.attachEffects_)) return false;
      if(!attachBuffs_.Equals(other.attachBuffs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (castData_ != null) hash ^= CastData.GetHashCode();
      hash ^= attachEffects_.GetHashCode();
      hash ^= attachBuffs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (castData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CastData);
      }
      attachEffects_.WriteTo(output, _repeated_attachEffects_codec);
      attachBuffs_.WriteTo(output, _repeated_attachBuffs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (castData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CastData);
      }
      attachEffects_.WriteTo(ref output, _repeated_attachEffects_codec);
      attachBuffs_.WriteTo(ref output, _repeated_attachBuffs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (castData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CastData);
      }
      size += attachEffects_.CalculateSize(_repeated_attachEffects_codec);
      size += attachBuffs_.CalculateSize(_repeated_attachBuffs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FrameSkillCastDataPb other) {
      if (other == null) {
        return;
      }
      if (other.castData_ != null) {
        if (castData_ == null) {
          CastData = new global::MetaVirus.Battle.Record.SkillCastDataPb();
        }
        CastData.MergeFrom(other.CastData);
      }
      attachEffects_.Add(other.attachEffects_);
      attachBuffs_.Add(other.attachBuffs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (castData_ == null) {
              CastData = new global::MetaVirus.Battle.Record.SkillCastDataPb();
            }
            input.ReadMessage(CastData);
            break;
          }
          case 18: {
            attachEffects_.AddEntriesFrom(input, _repeated_attachEffects_codec);
            break;
          }
          case 26: {
            attachBuffs_.AddEntriesFrom(input, _repeated_attachBuffs_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (castData_ == null) {
              CastData = new global::MetaVirus.Battle.Record.SkillCastDataPb();
            }
            input.ReadMessage(CastData);
            break;
          }
          case 18: {
            attachEffects_.AddEntriesFrom(ref input, _repeated_attachEffects_codec);
            break;
          }
          case 26: {
            attachBuffs_.AddEntriesFrom(ref input, _repeated_attachBuffs_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
