// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SkillCastActionFrame.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Battle.Record {

  /// <summary>Holder for reflection information generated from SkillCastActionFrame.proto</summary>
  public static partial class SkillCastActionFrameReflection {

    #region Descriptor
    /// <summary>File descriptor for SkillCastActionFrame.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SkillCastActionFrameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpTa2lsbENhc3RBY3Rpb25GcmFtZS5wcm90bxIXTWV0YVZpcnVzLmJhdHRs",
            "ZS5yZWNvcmQaGEZyYW1lU2tpbGxDYXN0RGF0YS5wcm90byKzAQoWU2tpbGxD",
            "YXN0QWN0aW9uRnJhbWVQYhIRCglmcmFtZVR5cGUYASABKAUSEQoJZnJhbWVU",
            "aW1lGAIgASgFEg0KBXNyY0lkGAMgASgFEg8KB3NraWxsSWQYBCABKAUSEgoK",
            "c2tpbGxMZXZlbBgFIAEoBRI/CghjYXN0TGlzdBgGIAMoCzItLk1ldGFWaXJ1",
            "cy5iYXR0bGUucmVjb3JkLkZyYW1lU2tpbGxDYXN0RGF0YVBiQjoKG2NvbS5t",
            "ZXRhdmlydXMuYmF0dGxlLnJlY29yZEIZU2tpbGxDYXN0QWN0aW9uRnJhbWVQ",
            "Qk91dFABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MetaVirus.Battle.Record.FrameSkillCastDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Battle.Record.SkillCastActionFramePb), global::MetaVirus.Battle.Record.SkillCastActionFramePb.Parser, new[]{ "FrameType", "FrameTime", "SrcId", "SkillId", "SkillLevel", "CastList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SkillCastActionFramePb : pb::IMessage<SkillCastActionFramePb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SkillCastActionFramePb> _parser = new pb::MessageParser<SkillCastActionFramePb>(() => new SkillCastActionFramePb());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SkillCastActionFramePb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Battle.Record.SkillCastActionFrameReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkillCastActionFramePb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkillCastActionFramePb(SkillCastActionFramePb other) : this() {
      frameType_ = other.frameType_;
      frameTime_ = other.frameTime_;
      srcId_ = other.srcId_;
      skillId_ = other.skillId_;
      skillLevel_ = other.skillLevel_;
      castList_ = other.castList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkillCastActionFramePb Clone() {
      return new SkillCastActionFramePb(this);
    }

    /// <summary>Field number for the "frameType" field.</summary>
    public const int FrameTypeFieldNumber = 1;
    private int frameType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FrameType {
      get { return frameType_; }
      set {
        frameType_ = value;
      }
    }

    /// <summary>Field number for the "frameTime" field.</summary>
    public const int FrameTimeFieldNumber = 2;
    private int frameTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FrameTime {
      get { return frameTime_; }
      set {
        frameTime_ = value;
      }
    }

    /// <summary>Field number for the "srcId" field.</summary>
    public const int SrcIdFieldNumber = 3;
    private int srcId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SrcId {
      get { return srcId_; }
      set {
        srcId_ = value;
      }
    }

    /// <summary>Field number for the "skillId" field.</summary>
    public const int SkillIdFieldNumber = 4;
    private int skillId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SkillId {
      get { return skillId_; }
      set {
        skillId_ = value;
      }
    }

    /// <summary>Field number for the "skillLevel" field.</summary>
    public const int SkillLevelFieldNumber = 5;
    private int skillLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SkillLevel {
      get { return skillLevel_; }
      set {
        skillLevel_ = value;
      }
    }

    /// <summary>Field number for the "castList" field.</summary>
    public const int CastListFieldNumber = 6;
    private static readonly pb::FieldCodec<global::MetaVirus.Battle.Record.FrameSkillCastDataPb> _repeated_castList_codec
        = pb::FieldCodec.ForMessage(50, global::MetaVirus.Battle.Record.FrameSkillCastDataPb.Parser);
    private readonly pbc::RepeatedField<global::MetaVirus.Battle.Record.FrameSkillCastDataPb> castList_ = new pbc::RepeatedField<global::MetaVirus.Battle.Record.FrameSkillCastDataPb>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MetaVirus.Battle.Record.FrameSkillCastDataPb> CastList {
      get { return castList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SkillCastActionFramePb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SkillCastActionFramePb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FrameType != other.FrameType) return false;
      if (FrameTime != other.FrameTime) return false;
      if (SrcId != other.SrcId) return false;
      if (SkillId != other.SkillId) return false;
      if (SkillLevel != other.SkillLevel) return false;
      if(!castList_.Equals(other.castList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FrameType != 0) hash ^= FrameType.GetHashCode();
      if (FrameTime != 0) hash ^= FrameTime.GetHashCode();
      if (SrcId != 0) hash ^= SrcId.GetHashCode();
      if (SkillId != 0) hash ^= SkillId.GetHashCode();
      if (SkillLevel != 0) hash ^= SkillLevel.GetHashCode();
      hash ^= castList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrameType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FrameType);
      }
      if (FrameTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FrameTime);
      }
      if (SrcId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SrcId);
      }
      if (SkillId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SkillId);
      }
      if (SkillLevel != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SkillLevel);
      }
      castList_.WriteTo(output, _repeated_castList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrameType != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(FrameType);
      }
      if (FrameTime != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FrameTime);
      }
      if (SrcId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SrcId);
      }
      if (SkillId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SkillId);
      }
      if (SkillLevel != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SkillLevel);
      }
      castList_.WriteTo(ref output, _repeated_castList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FrameType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrameType);
      }
      if (FrameTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrameTime);
      }
      if (SrcId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SrcId);
      }
      if (SkillId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillId);
      }
      if (SkillLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillLevel);
      }
      size += castList_.CalculateSize(_repeated_castList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SkillCastActionFramePb other) {
      if (other == null) {
        return;
      }
      if (other.FrameType != 0) {
        FrameType = other.FrameType;
      }
      if (other.FrameTime != 0) {
        FrameTime = other.FrameTime;
      }
      if (other.SrcId != 0) {
        SrcId = other.SrcId;
      }
      if (other.SkillId != 0) {
        SkillId = other.SkillId;
      }
      if (other.SkillLevel != 0) {
        SkillLevel = other.SkillLevel;
      }
      castList_.Add(other.castList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FrameType = input.ReadInt32();
            break;
          }
          case 16: {
            FrameTime = input.ReadInt32();
            break;
          }
          case 24: {
            SrcId = input.ReadInt32();
            break;
          }
          case 32: {
            SkillId = input.ReadInt32();
            break;
          }
          case 40: {
            SkillLevel = input.ReadInt32();
            break;
          }
          case 50: {
            castList_.AddEntriesFrom(input, _repeated_castList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FrameType = input.ReadInt32();
            break;
          }
          case 16: {
            FrameTime = input.ReadInt32();
            break;
          }
          case 24: {
            SrcId = input.ReadInt32();
            break;
          }
          case 32: {
            SkillId = input.ReadInt32();
            break;
          }
          case 40: {
            SkillLevel = input.ReadInt32();
            break;
          }
          case 50: {
            castList_.AddEntriesFrom(ref input, _repeated_castList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
