// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WorldMessages/arena/ArenaTopRankListResponseSc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Net.Messages.Arena {

  /// <summary>Holder for reflection information generated from WorldMessages/arena/ArenaTopRankListResponseSc.proto</summary>
  public static partial class ArenaTopRankListResponseScReflection {

    #region Descriptor
    /// <summary>File descriptor for WorldMessages/arena/ArenaTopRankListResponseSc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ArenaTopRankListResponseScReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRXb3JsZE1lc3NhZ2VzL2FyZW5hL0FyZW5hVG9wUmFua0xpc3RSZXNwb25z",
            "ZVNjLnByb3RvEhxNZXRhVmlydXMuTmV0Lk1lc3NhZ2VzLkFyZW5hGjFwcm90",
            "b3MvV29ybGRNZXNzYWdlcy9jb21tb24vQXJlbmFQbGF5ZXJJbmZvLnByb3Rv",
            "IoYBChxBcmVuYVRvcFJhbmtMaXN0UmVzcG9uc2VTY1BiEhQKB2FyZW5hSWQY",
            "ASABKAVIAIgBARJECgpwbGF5ZXJJbmZvGAIgAygLMjAuTWV0YVZpcnVzLk5l",
            "dC5NZXNzYWdlcy5Db21tb24uUEJBcmVuYVBsYXllckluZm9CCgoIX2FyZW5h",
            "SWRCSAojY29tLm1ldGF2aXJ1cy5uZXQubWVzc2FnZXMucGIuYXJlbmFCH0Fy",
            "ZW5hVG9wUmFua0xpc3RSZXNwb25zZVNjUGJPdXRQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MetaVirus.Net.Messages.Common.ArenaPlayerInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Net.Messages.Arena.ArenaTopRankListResponseScPb), global::MetaVirus.Net.Messages.Arena.ArenaTopRankListResponseScPb.Parser, new[]{ "ArenaId", "PlayerInfo" }, new[]{ "ArenaId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  ///获取指定竞技场的前n名玩家数据，数量由服务器决定
  /// </summary>
  public sealed partial class ArenaTopRankListResponseScPb : pb::IMessage<ArenaTopRankListResponseScPb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ArenaTopRankListResponseScPb> _parser = new pb::MessageParser<ArenaTopRankListResponseScPb>(() => new ArenaTopRankListResponseScPb());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ArenaTopRankListResponseScPb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Net.Messages.Arena.ArenaTopRankListResponseScReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ArenaTopRankListResponseScPb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ArenaTopRankListResponseScPb(ArenaTopRankListResponseScPb other) : this() {
      _hasBits0 = other._hasBits0;
      arenaId_ = other.arenaId_;
      playerInfo_ = other.playerInfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ArenaTopRankListResponseScPb Clone() {
      return new ArenaTopRankListResponseScPb(this);
    }

    /// <summary>Field number for the "arenaId" field.</summary>
    public const int ArenaIdFieldNumber = 1;
    private int arenaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ArenaId {
      get { if ((_hasBits0 & 1) != 0) { return arenaId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        arenaId_ = value;
      }
    }
    /// <summary>Gets whether the "arenaId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasArenaId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "arenaId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearArenaId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "playerInfo" field.</summary>
    public const int PlayerInfoFieldNumber = 2;
    private static readonly pb::FieldCodec<global::MetaVirus.Net.Messages.Common.PBArenaPlayerInfo> _repeated_playerInfo_codec
        = pb::FieldCodec.ForMessage(18, global::MetaVirus.Net.Messages.Common.PBArenaPlayerInfo.Parser);
    private readonly pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBArenaPlayerInfo> playerInfo_ = new pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBArenaPlayerInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBArenaPlayerInfo> PlayerInfo {
      get { return playerInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ArenaTopRankListResponseScPb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ArenaTopRankListResponseScPb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ArenaId != other.ArenaId) return false;
      if(!playerInfo_.Equals(other.playerInfo_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasArenaId) hash ^= ArenaId.GetHashCode();
      hash ^= playerInfo_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasArenaId) {
        output.WriteRawTag(8);
        output.WriteInt32(ArenaId);
      }
      playerInfo_.WriteTo(output, _repeated_playerInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasArenaId) {
        output.WriteRawTag(8);
        output.WriteInt32(ArenaId);
      }
      playerInfo_.WriteTo(ref output, _repeated_playerInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasArenaId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ArenaId);
      }
      size += playerInfo_.CalculateSize(_repeated_playerInfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ArenaTopRankListResponseScPb other) {
      if (other == null) {
        return;
      }
      if (other.HasArenaId) {
        ArenaId = other.ArenaId;
      }
      playerInfo_.Add(other.playerInfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ArenaId = input.ReadInt32();
            break;
          }
          case 18: {
            playerInfo_.AddEntriesFrom(input, _repeated_playerInfo_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ArenaId = input.ReadInt32();
            break;
          }
          case 18: {
            playerInfo_.AddEntriesFrom(ref input, _repeated_playerInfo_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
