// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/WorldMessages/common/ArenaPlayerRecord.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Net.Messages.Common {

  /// <summary>Holder for reflection information generated from protos/WorldMessages/common/ArenaPlayerRecord.proto</summary>
  public static partial class ArenaPlayerRecordReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/WorldMessages/common/ArenaPlayerRecord.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ArenaPlayerRecordReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNwcm90b3MvV29ybGRNZXNzYWdlcy9jb21tb24vQXJlbmFQbGF5ZXJSZWNv",
            "cmQucHJvdG8SHU1ldGFWaXJ1cy5OZXQuTWVzc2FnZXMuQ29tbW9uIoMDChNQ",
            "QkFyZW5hUGxheWVyUmVjb3JkEhUKCHJlY29yZElkGAEgASgFSACIAQESFQoI",
            "YXR0YWNrSWQYAiABKAVIAYgBARIXCgphdHRhY2tOYW1lGAMgASgJSAKIAQES",
            "FgoJZGVmZW5jZUlkGAQgASgFSAOIAQESGAoLZGVmZW5jZU5hbWUYBSABKAlI",
            "BIgBARITCgZyZXN1bHQYBiABKAVIBYgBARIXCgpiYXR0bGVUaW1lGAcgASgD",
            "SAaIAQESIAoTYmF0dGxlUmVjb3JkVmVyc2lvbhgIIAEoBUgHiAEBEhkKDGJh",
            "dHRsZVJlY29yZBgJIAEoDEgIiAEBQgsKCV9yZWNvcmRJZEILCglfYXR0YWNr",
            "SWRCDQoLX2F0dGFja05hbWVCDAoKX2RlZmVuY2VJZEIOCgxfZGVmZW5jZU5h",
            "bWVCCQoHX3Jlc3VsdEINCgtfYmF0dGxlVGltZUIWChRfYmF0dGxlUmVjb3Jk",
            "VmVyc2lvbkIPCg1fYmF0dGxlUmVjb3JkQkIKJGNvbS5tZXRhdmlydXMubmV0",
            "Lm1lc3NhZ2VzLnBiLmNvbW1vbkIYUEJBcmVuYVBsYXllclJlY29yZFBiT3V0",
            "UAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Net.Messages.Common.PBArenaPlayerRecord), global::MetaVirus.Net.Messages.Common.PBArenaPlayerRecord.Parser, new[]{ "RecordId", "AttackId", "AttackName", "DefenceId", "DefenceName", "Result", "BattleTime", "BattleRecordVersion", "BattleRecord" }, new[]{ "RecordId", "AttackId", "AttackName", "DefenceId", "DefenceName", "Result", "BattleTime", "BattleRecordVersion", "BattleRecord" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PBArenaPlayerRecord : pb::IMessage<PBArenaPlayerRecord>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBArenaPlayerRecord> _parser = new pb::MessageParser<PBArenaPlayerRecord>(() => new PBArenaPlayerRecord());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBArenaPlayerRecord> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Net.Messages.Common.ArenaPlayerRecordReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBArenaPlayerRecord() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBArenaPlayerRecord(PBArenaPlayerRecord other) : this() {
      _hasBits0 = other._hasBits0;
      recordId_ = other.recordId_;
      attackId_ = other.attackId_;
      attackName_ = other.attackName_;
      defenceId_ = other.defenceId_;
      defenceName_ = other.defenceName_;
      result_ = other.result_;
      battleTime_ = other.battleTime_;
      battleRecordVersion_ = other.battleRecordVersion_;
      battleRecord_ = other.battleRecord_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBArenaPlayerRecord Clone() {
      return new PBArenaPlayerRecord(this);
    }

    /// <summary>Field number for the "recordId" field.</summary>
    public const int RecordIdFieldNumber = 1;
    private int recordId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RecordId {
      get { if ((_hasBits0 & 1) != 0) { return recordId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        recordId_ = value;
      }
    }
    /// <summary>Gets whether the "recordId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRecordId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "recordId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRecordId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "attackId" field.</summary>
    public const int AttackIdFieldNumber = 2;
    private int attackId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AttackId {
      get { if ((_hasBits0 & 2) != 0) { return attackId_; } else { return 0; } }
      set {
        _hasBits0 |= 2;
        attackId_ = value;
      }
    }
    /// <summary>Gets whether the "attackId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAttackId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "attackId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAttackId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "attackName" field.</summary>
    public const int AttackNameFieldNumber = 3;
    private string attackName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AttackName {
      get { return attackName_ ?? ""; }
      set {
        attackName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "attackName" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAttackName {
      get { return attackName_ != null; }
    }
    /// <summary>Clears the value of the "attackName" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAttackName() {
      attackName_ = null;
    }

    /// <summary>Field number for the "defenceId" field.</summary>
    public const int DefenceIdFieldNumber = 4;
    private int defenceId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DefenceId {
      get { if ((_hasBits0 & 4) != 0) { return defenceId_; } else { return 0; } }
      set {
        _hasBits0 |= 4;
        defenceId_ = value;
      }
    }
    /// <summary>Gets whether the "defenceId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDefenceId {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "defenceId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDefenceId() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "defenceName" field.</summary>
    public const int DefenceNameFieldNumber = 5;
    private string defenceName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DefenceName {
      get { return defenceName_ ?? ""; }
      set {
        defenceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "defenceName" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDefenceName {
      get { return defenceName_ != null; }
    }
    /// <summary>Clears the value of the "defenceName" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDefenceName() {
      defenceName_ = null;
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 6;
    private int result_;
    /// <summary>
    ///*
    /// 战斗结果
    /// 0=win 1=draw 2=lose
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Result {
      get { if ((_hasBits0 & 8) != 0) { return result_; } else { return 0; } }
      set {
        _hasBits0 |= 8;
        result_ = value;
      }
    }
    /// <summary>Gets whether the "result" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasResult {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "result" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResult() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "battleTime" field.</summary>
    public const int BattleTimeFieldNumber = 7;
    private long battleTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long BattleTime {
      get { if ((_hasBits0 & 16) != 0) { return battleTime_; } else { return 0L; } }
      set {
        _hasBits0 |= 16;
        battleTime_ = value;
      }
    }
    /// <summary>Gets whether the "battleTime" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBattleTime {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "battleTime" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBattleTime() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "battleRecordVersion" field.</summary>
    public const int BattleRecordVersionFieldNumber = 8;
    private int battleRecordVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BattleRecordVersion {
      get { if ((_hasBits0 & 32) != 0) { return battleRecordVersion_; } else { return 0; } }
      set {
        _hasBits0 |= 32;
        battleRecordVersion_ = value;
      }
    }
    /// <summary>Gets whether the "battleRecordVersion" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBattleRecordVersion {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "battleRecordVersion" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBattleRecordVersion() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "battleRecord" field.</summary>
    public const int BattleRecordFieldNumber = 9;
    private pb::ByteString battleRecord_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BattleRecord {
      get { return battleRecord_ ?? pb::ByteString.Empty; }
      set {
        battleRecord_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "battleRecord" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBattleRecord {
      get { return battleRecord_ != null; }
    }
    /// <summary>Clears the value of the "battleRecord" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBattleRecord() {
      battleRecord_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBArenaPlayerRecord);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBArenaPlayerRecord other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RecordId != other.RecordId) return false;
      if (AttackId != other.AttackId) return false;
      if (AttackName != other.AttackName) return false;
      if (DefenceId != other.DefenceId) return false;
      if (DefenceName != other.DefenceName) return false;
      if (Result != other.Result) return false;
      if (BattleTime != other.BattleTime) return false;
      if (BattleRecordVersion != other.BattleRecordVersion) return false;
      if (BattleRecord != other.BattleRecord) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRecordId) hash ^= RecordId.GetHashCode();
      if (HasAttackId) hash ^= AttackId.GetHashCode();
      if (HasAttackName) hash ^= AttackName.GetHashCode();
      if (HasDefenceId) hash ^= DefenceId.GetHashCode();
      if (HasDefenceName) hash ^= DefenceName.GetHashCode();
      if (HasResult) hash ^= Result.GetHashCode();
      if (HasBattleTime) hash ^= BattleTime.GetHashCode();
      if (HasBattleRecordVersion) hash ^= BattleRecordVersion.GetHashCode();
      if (HasBattleRecord) hash ^= BattleRecord.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRecordId) {
        output.WriteRawTag(8);
        output.WriteInt32(RecordId);
      }
      if (HasAttackId) {
        output.WriteRawTag(16);
        output.WriteInt32(AttackId);
      }
      if (HasAttackName) {
        output.WriteRawTag(26);
        output.WriteString(AttackName);
      }
      if (HasDefenceId) {
        output.WriteRawTag(32);
        output.WriteInt32(DefenceId);
      }
      if (HasDefenceName) {
        output.WriteRawTag(42);
        output.WriteString(DefenceName);
      }
      if (HasResult) {
        output.WriteRawTag(48);
        output.WriteInt32(Result);
      }
      if (HasBattleTime) {
        output.WriteRawTag(56);
        output.WriteInt64(BattleTime);
      }
      if (HasBattleRecordVersion) {
        output.WriteRawTag(64);
        output.WriteInt32(BattleRecordVersion);
      }
      if (HasBattleRecord) {
        output.WriteRawTag(74);
        output.WriteBytes(BattleRecord);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRecordId) {
        output.WriteRawTag(8);
        output.WriteInt32(RecordId);
      }
      if (HasAttackId) {
        output.WriteRawTag(16);
        output.WriteInt32(AttackId);
      }
      if (HasAttackName) {
        output.WriteRawTag(26);
        output.WriteString(AttackName);
      }
      if (HasDefenceId) {
        output.WriteRawTag(32);
        output.WriteInt32(DefenceId);
      }
      if (HasDefenceName) {
        output.WriteRawTag(42);
        output.WriteString(DefenceName);
      }
      if (HasResult) {
        output.WriteRawTag(48);
        output.WriteInt32(Result);
      }
      if (HasBattleTime) {
        output.WriteRawTag(56);
        output.WriteInt64(BattleTime);
      }
      if (HasBattleRecordVersion) {
        output.WriteRawTag(64);
        output.WriteInt32(BattleRecordVersion);
      }
      if (HasBattleRecord) {
        output.WriteRawTag(74);
        output.WriteBytes(BattleRecord);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasRecordId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RecordId);
      }
      if (HasAttackId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttackId);
      }
      if (HasAttackName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AttackName);
      }
      if (HasDefenceId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DefenceId);
      }
      if (HasDefenceName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DefenceName);
      }
      if (HasResult) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
      }
      if (HasBattleTime) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BattleTime);
      }
      if (HasBattleRecordVersion) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BattleRecordVersion);
      }
      if (HasBattleRecord) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BattleRecord);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBArenaPlayerRecord other) {
      if (other == null) {
        return;
      }
      if (other.HasRecordId) {
        RecordId = other.RecordId;
      }
      if (other.HasAttackId) {
        AttackId = other.AttackId;
      }
      if (other.HasAttackName) {
        AttackName = other.AttackName;
      }
      if (other.HasDefenceId) {
        DefenceId = other.DefenceId;
      }
      if (other.HasDefenceName) {
        DefenceName = other.DefenceName;
      }
      if (other.HasResult) {
        Result = other.Result;
      }
      if (other.HasBattleTime) {
        BattleTime = other.BattleTime;
      }
      if (other.HasBattleRecordVersion) {
        BattleRecordVersion = other.BattleRecordVersion;
      }
      if (other.HasBattleRecord) {
        BattleRecord = other.BattleRecord;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RecordId = input.ReadInt32();
            break;
          }
          case 16: {
            AttackId = input.ReadInt32();
            break;
          }
          case 26: {
            AttackName = input.ReadString();
            break;
          }
          case 32: {
            DefenceId = input.ReadInt32();
            break;
          }
          case 42: {
            DefenceName = input.ReadString();
            break;
          }
          case 48: {
            Result = input.ReadInt32();
            break;
          }
          case 56: {
            BattleTime = input.ReadInt64();
            break;
          }
          case 64: {
            BattleRecordVersion = input.ReadInt32();
            break;
          }
          case 74: {
            BattleRecord = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RecordId = input.ReadInt32();
            break;
          }
          case 16: {
            AttackId = input.ReadInt32();
            break;
          }
          case 26: {
            AttackName = input.ReadString();
            break;
          }
          case 32: {
            DefenceId = input.ReadInt32();
            break;
          }
          case 42: {
            DefenceName = input.ReadString();
            break;
          }
          case 48: {
            Result = input.ReadInt32();
            break;
          }
          case 56: {
            BattleTime = input.ReadInt64();
            break;
          }
          case 64: {
            BattleRecordVersion = input.ReadInt32();
            break;
          }
          case 74: {
            BattleRecord = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
