// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/WorldMessages/common/BattleFormationDetailSlot.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Net.Messages.Common {

  /// <summary>Holder for reflection information generated from protos/WorldMessages/common/BattleFormationDetailSlot.proto</summary>
  public static partial class BattleFormationDetailSlotReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/WorldMessages/common/BattleFormationDetailSlot.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleFormationDetailSlotReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cjtwcm90b3MvV29ybGRNZXNzYWdlcy9jb21tb24vQmF0dGxlRm9ybWF0aW9u",
            "RGV0YWlsU2xvdC5wcm90bxIdTWV0YVZpcnVzLk5ldC5NZXNzYWdlcy5Db21t",
            "b24iyAMKG1BCQmF0dGxlRm9ybWF0aW9uRGV0YWlsU2xvdBITCgZzbG90SWQY",
            "ASABKAVIAIgBARIVCghpdGVtVHlwZRgCIAEoBUgBiAEBEhMKBml0ZW1JZBgD",
            "IAEoBUgCiAEBEhYKCWl0ZW1SZXNJZBgEIAEoBUgDiAEBEhYKCWl0ZW1MZXZl",
            "bBgFIAEoBUgEiAEBEhgKC2l0ZW1RdWFsaXR5GAYgASgFSAWIAQESGAoLY2hh",
            "cmFjdGVySWQYByABKAVIBogBARIYCgtncm93VGFibGVJZBgIIAEoBUgHiAEB",
            "EhsKDmxldmVsVXBUYWJsZUlkGAkgASgFSAiIAQESEgoKYXR0cmlidXRlcxgK",
            "IAMoBRITCgtyZXNpc3RhbmNlcxgLIAMoBRIVCghpdGVtTmFtZRgMIAEoCUgJ",
            "iAEBQgkKB19zbG90SWRCCwoJX2l0ZW1UeXBlQgkKB19pdGVtSWRCDAoKX2l0",
            "ZW1SZXNJZEIMCgpfaXRlbUxldmVsQg4KDF9pdGVtUXVhbGl0eUIOCgxfY2hh",
            "cmFjdGVySWRCDgoMX2dyb3dUYWJsZUlkQhEKD19sZXZlbFVwVGFibGVJZEIL",
            "CglfaXRlbU5hbWVCSAokY29tLm1ldGF2aXJ1cy5uZXQubWVzc2FnZXMucGIu",
            "Y29tbW9uQh5CYXR0bGVGb3JtYXRpb25EZXRhaWxTbG90UGJPdXRQAWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Net.Messages.Common.PBBattleFormationDetailSlot), global::MetaVirus.Net.Messages.Common.PBBattleFormationDetailSlot.Parser, new[]{ "SlotId", "ItemType", "ItemId", "ItemResId", "ItemLevel", "ItemQuality", "CharacterId", "GrowTableId", "LevelUpTableId", "Attributes", "Resistances", "ItemName" }, new[]{ "SlotId", "ItemType", "ItemId", "ItemResId", "ItemLevel", "ItemQuality", "CharacterId", "GrowTableId", "LevelUpTableId", "ItemName" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PBBattleFormationDetailSlot : pb::IMessage<PBBattleFormationDetailSlot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBBattleFormationDetailSlot> _parser = new pb::MessageParser<PBBattleFormationDetailSlot>(() => new PBBattleFormationDetailSlot());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBBattleFormationDetailSlot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Net.Messages.Common.BattleFormationDetailSlotReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBBattleFormationDetailSlot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBBattleFormationDetailSlot(PBBattleFormationDetailSlot other) : this() {
      _hasBits0 = other._hasBits0;
      slotId_ = other.slotId_;
      itemType_ = other.itemType_;
      itemId_ = other.itemId_;
      itemResId_ = other.itemResId_;
      itemLevel_ = other.itemLevel_;
      itemQuality_ = other.itemQuality_;
      characterId_ = other.characterId_;
      growTableId_ = other.growTableId_;
      levelUpTableId_ = other.levelUpTableId_;
      attributes_ = other.attributes_.Clone();
      resistances_ = other.resistances_.Clone();
      itemName_ = other.itemName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBBattleFormationDetailSlot Clone() {
      return new PBBattleFormationDetailSlot(this);
    }

    /// <summary>Field number for the "slotId" field.</summary>
    public const int SlotIdFieldNumber = 1;
    private int slotId_;
    /// <summary>
    ///*
    /// slot id  1 to 9
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SlotId {
      get { if ((_hasBits0 & 1) != 0) { return slotId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        slotId_ = value;
      }
    }
    /// <summary>Gets whether the "slotId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSlotId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "slotId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSlotId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "itemType" field.</summary>
    public const int ItemTypeFieldNumber = 2;
    private int itemType_;
    /// <summary>
    ///*
    /// 类型，0=PetData, 1=MonsterData
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemType {
      get { if ((_hasBits0 & 2) != 0) { return itemType_; } else { return 0; } }
      set {
        _hasBits0 |= 2;
        itemType_ = value;
      }
    }
    /// <summary>Gets whether the "itemType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasItemType {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "itemType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearItemType() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "itemId" field.</summary>
    public const int ItemIdFieldNumber = 3;
    private int itemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemId {
      get { if ((_hasBits0 & 4) != 0) { return itemId_; } else { return 0; } }
      set {
        _hasBits0 |= 4;
        itemId_ = value;
      }
    }
    /// <summary>Gets whether the "itemId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasItemId {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "itemId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearItemId() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "itemResId" field.</summary>
    public const int ItemResIdFieldNumber = 4;
    private int itemResId_;
    /// <summary>
    ///*
    /// 资源id，对应MonsterData或者PetData
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemResId {
      get { if ((_hasBits0 & 8) != 0) { return itemResId_; } else { return 0; } }
      set {
        _hasBits0 |= 8;
        itemResId_ = value;
      }
    }
    /// <summary>Gets whether the "itemResId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasItemResId {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "itemResId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearItemResId() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "itemLevel" field.</summary>
    public const int ItemLevelFieldNumber = 5;
    private int itemLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemLevel {
      get { if ((_hasBits0 & 16) != 0) { return itemLevel_; } else { return 0; } }
      set {
        _hasBits0 |= 16;
        itemLevel_ = value;
      }
    }
    /// <summary>Gets whether the "itemLevel" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasItemLevel {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "itemLevel" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearItemLevel() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "itemQuality" field.</summary>
    public const int ItemQualityFieldNumber = 6;
    private int itemQuality_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemQuality {
      get { if ((_hasBits0 & 32) != 0) { return itemQuality_; } else { return 0; } }
      set {
        _hasBits0 |= 32;
        itemQuality_ = value;
      }
    }
    /// <summary>Gets whether the "itemQuality" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasItemQuality {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "itemQuality" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearItemQuality() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "characterId" field.</summary>
    public const int CharacterIdFieldNumber = 7;
    private int characterId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CharacterId {
      get { if ((_hasBits0 & 64) != 0) { return characterId_; } else { return 0; } }
      set {
        _hasBits0 |= 64;
        characterId_ = value;
      }
    }
    /// <summary>Gets whether the "characterId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCharacterId {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "characterId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCharacterId() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "growTableId" field.</summary>
    public const int GrowTableIdFieldNumber = 8;
    private int growTableId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GrowTableId {
      get { if ((_hasBits0 & 128) != 0) { return growTableId_; } else { return 0; } }
      set {
        _hasBits0 |= 128;
        growTableId_ = value;
      }
    }
    /// <summary>Gets whether the "growTableId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGrowTableId {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "growTableId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGrowTableId() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "levelUpTableId" field.</summary>
    public const int LevelUpTableIdFieldNumber = 9;
    private int levelUpTableId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LevelUpTableId {
      get { if ((_hasBits0 & 256) != 0) { return levelUpTableId_; } else { return 0; } }
      set {
        _hasBits0 |= 256;
        levelUpTableId_ = value;
      }
    }
    /// <summary>Gets whether the "levelUpTableId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLevelUpTableId {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "levelUpTableId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLevelUpTableId() {
      _hasBits0 &= ~256;
    }

    /// <summary>Field number for the "attributes" field.</summary>
    public const int AttributesFieldNumber = 10;
    private static readonly pb::FieldCodec<int> _repeated_attributes_codec
        = pb::FieldCodec.ForInt32(82);
    private readonly pbc::RepeatedField<int> attributes_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///*
    /// 计算完成后的属性值 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Attributes {
      get { return attributes_; }
    }

    /// <summary>Field number for the "resistances" field.</summary>
    public const int ResistancesFieldNumber = 11;
    private static readonly pb::FieldCodec<int> _repeated_resistances_codec
        = pb::FieldCodec.ForInt32(90);
    private readonly pbc::RepeatedField<int> resistances_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///*
    /// 计算完成后的抗性
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Resistances {
      get { return resistances_; }
    }

    /// <summary>Field number for the "itemName" field.</summary>
    public const int ItemNameFieldNumber = 12;
    private string itemName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ItemName {
      get { return itemName_ ?? ""; }
      set {
        itemName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "itemName" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasItemName {
      get { return itemName_ != null; }
    }
    /// <summary>Clears the value of the "itemName" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearItemName() {
      itemName_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBBattleFormationDetailSlot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBBattleFormationDetailSlot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SlotId != other.SlotId) return false;
      if (ItemType != other.ItemType) return false;
      if (ItemId != other.ItemId) return false;
      if (ItemResId != other.ItemResId) return false;
      if (ItemLevel != other.ItemLevel) return false;
      if (ItemQuality != other.ItemQuality) return false;
      if (CharacterId != other.CharacterId) return false;
      if (GrowTableId != other.GrowTableId) return false;
      if (LevelUpTableId != other.LevelUpTableId) return false;
      if(!attributes_.Equals(other.attributes_)) return false;
      if(!resistances_.Equals(other.resistances_)) return false;
      if (ItemName != other.ItemName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasSlotId) hash ^= SlotId.GetHashCode();
      if (HasItemType) hash ^= ItemType.GetHashCode();
      if (HasItemId) hash ^= ItemId.GetHashCode();
      if (HasItemResId) hash ^= ItemResId.GetHashCode();
      if (HasItemLevel) hash ^= ItemLevel.GetHashCode();
      if (HasItemQuality) hash ^= ItemQuality.GetHashCode();
      if (HasCharacterId) hash ^= CharacterId.GetHashCode();
      if (HasGrowTableId) hash ^= GrowTableId.GetHashCode();
      if (HasLevelUpTableId) hash ^= LevelUpTableId.GetHashCode();
      hash ^= attributes_.GetHashCode();
      hash ^= resistances_.GetHashCode();
      if (HasItemName) hash ^= ItemName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasSlotId) {
        output.WriteRawTag(8);
        output.WriteInt32(SlotId);
      }
      if (HasItemType) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemType);
      }
      if (HasItemId) {
        output.WriteRawTag(24);
        output.WriteInt32(ItemId);
      }
      if (HasItemResId) {
        output.WriteRawTag(32);
        output.WriteInt32(ItemResId);
      }
      if (HasItemLevel) {
        output.WriteRawTag(40);
        output.WriteInt32(ItemLevel);
      }
      if (HasItemQuality) {
        output.WriteRawTag(48);
        output.WriteInt32(ItemQuality);
      }
      if (HasCharacterId) {
        output.WriteRawTag(56);
        output.WriteInt32(CharacterId);
      }
      if (HasGrowTableId) {
        output.WriteRawTag(64);
        output.WriteInt32(GrowTableId);
      }
      if (HasLevelUpTableId) {
        output.WriteRawTag(72);
        output.WriteInt32(LevelUpTableId);
      }
      attributes_.WriteTo(output, _repeated_attributes_codec);
      resistances_.WriteTo(output, _repeated_resistances_codec);
      if (HasItemName) {
        output.WriteRawTag(98);
        output.WriteString(ItemName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasSlotId) {
        output.WriteRawTag(8);
        output.WriteInt32(SlotId);
      }
      if (HasItemType) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemType);
      }
      if (HasItemId) {
        output.WriteRawTag(24);
        output.WriteInt32(ItemId);
      }
      if (HasItemResId) {
        output.WriteRawTag(32);
        output.WriteInt32(ItemResId);
      }
      if (HasItemLevel) {
        output.WriteRawTag(40);
        output.WriteInt32(ItemLevel);
      }
      if (HasItemQuality) {
        output.WriteRawTag(48);
        output.WriteInt32(ItemQuality);
      }
      if (HasCharacterId) {
        output.WriteRawTag(56);
        output.WriteInt32(CharacterId);
      }
      if (HasGrowTableId) {
        output.WriteRawTag(64);
        output.WriteInt32(GrowTableId);
      }
      if (HasLevelUpTableId) {
        output.WriteRawTag(72);
        output.WriteInt32(LevelUpTableId);
      }
      attributes_.WriteTo(ref output, _repeated_attributes_codec);
      resistances_.WriteTo(ref output, _repeated_resistances_codec);
      if (HasItemName) {
        output.WriteRawTag(98);
        output.WriteString(ItemName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasSlotId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SlotId);
      }
      if (HasItemType) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemType);
      }
      if (HasItemId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
      }
      if (HasItemResId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemResId);
      }
      if (HasItemLevel) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemLevel);
      }
      if (HasItemQuality) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemQuality);
      }
      if (HasCharacterId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CharacterId);
      }
      if (HasGrowTableId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GrowTableId);
      }
      if (HasLevelUpTableId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LevelUpTableId);
      }
      size += attributes_.CalculateSize(_repeated_attributes_codec);
      size += resistances_.CalculateSize(_repeated_resistances_codec);
      if (HasItemName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBBattleFormationDetailSlot other) {
      if (other == null) {
        return;
      }
      if (other.HasSlotId) {
        SlotId = other.SlotId;
      }
      if (other.HasItemType) {
        ItemType = other.ItemType;
      }
      if (other.HasItemId) {
        ItemId = other.ItemId;
      }
      if (other.HasItemResId) {
        ItemResId = other.ItemResId;
      }
      if (other.HasItemLevel) {
        ItemLevel = other.ItemLevel;
      }
      if (other.HasItemQuality) {
        ItemQuality = other.ItemQuality;
      }
      if (other.HasCharacterId) {
        CharacterId = other.CharacterId;
      }
      if (other.HasGrowTableId) {
        GrowTableId = other.GrowTableId;
      }
      if (other.HasLevelUpTableId) {
        LevelUpTableId = other.LevelUpTableId;
      }
      attributes_.Add(other.attributes_);
      resistances_.Add(other.resistances_);
      if (other.HasItemName) {
        ItemName = other.ItemName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SlotId = input.ReadInt32();
            break;
          }
          case 16: {
            ItemType = input.ReadInt32();
            break;
          }
          case 24: {
            ItemId = input.ReadInt32();
            break;
          }
          case 32: {
            ItemResId = input.ReadInt32();
            break;
          }
          case 40: {
            ItemLevel = input.ReadInt32();
            break;
          }
          case 48: {
            ItemQuality = input.ReadInt32();
            break;
          }
          case 56: {
            CharacterId = input.ReadInt32();
            break;
          }
          case 64: {
            GrowTableId = input.ReadInt32();
            break;
          }
          case 72: {
            LevelUpTableId = input.ReadInt32();
            break;
          }
          case 82:
          case 80: {
            attributes_.AddEntriesFrom(input, _repeated_attributes_codec);
            break;
          }
          case 90:
          case 88: {
            resistances_.AddEntriesFrom(input, _repeated_resistances_codec);
            break;
          }
          case 98: {
            ItemName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SlotId = input.ReadInt32();
            break;
          }
          case 16: {
            ItemType = input.ReadInt32();
            break;
          }
          case 24: {
            ItemId = input.ReadInt32();
            break;
          }
          case 32: {
            ItemResId = input.ReadInt32();
            break;
          }
          case 40: {
            ItemLevel = input.ReadInt32();
            break;
          }
          case 48: {
            ItemQuality = input.ReadInt32();
            break;
          }
          case 56: {
            CharacterId = input.ReadInt32();
            break;
          }
          case 64: {
            GrowTableId = input.ReadInt32();
            break;
          }
          case 72: {
            LevelUpTableId = input.ReadInt32();
            break;
          }
          case 82:
          case 80: {
            attributes_.AddEntriesFrom(ref input, _repeated_attributes_codec);
            break;
          }
          case 90:
          case 88: {
            resistances_.AddEntriesFrom(ref input, _repeated_resistances_codec);
            break;
          }
          case 98: {
            ItemName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
