// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WorldMessages/user/CreateActorRequestCs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Net.Messages.User {

  /// <summary>Holder for reflection information generated from WorldMessages/user/CreateActorRequestCs.proto</summary>
  public static partial class CreateActorRequestCsReflection {

    #region Descriptor
    /// <summary>File descriptor for WorldMessages/user/CreateActorRequestCs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CreateActorRequestCsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1Xb3JsZE1lc3NhZ2VzL3VzZXIvQ3JlYXRlQWN0b3JSZXF1ZXN0Q3MucHJv",
            "dG8SG01ldGFWaXJ1cy5OZXQuTWVzc2FnZXMuVXNlciJsChZDcmVhdGVBY3Rv",
            "clJlcXVlc3RDc1BiEhYKCWFjdG9yTmFtZRgBIAEoCUgAiAEBEhoKDWF2YXRh",
            "clNldHRpbmcYAiABKANIAYgBAUIMCgpfYWN0b3JOYW1lQhAKDl9hdmF0YXJT",
            "ZXR0aW5nQkEKImNvbS5tZXRhdmlydXMubmV0Lm1lc3NhZ2VzLnBiLnVzZXJC",
            "GUNyZWF0ZUFjdG9yUmVxdWVzdENzUGJPdXRQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Net.Messages.User.CreateActorRequestCsPb), global::MetaVirus.Net.Messages.User.CreateActorRequestCsPb.Parser, new[]{ "ActorName", "AvatarSetting" }, new[]{ "ActorName", "AvatarSetting" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CreateActorRequestCsPb : pb::IMessage<CreateActorRequestCsPb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateActorRequestCsPb> _parser = new pb::MessageParser<CreateActorRequestCsPb>(() => new CreateActorRequestCsPb());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateActorRequestCsPb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Net.Messages.User.CreateActorRequestCsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateActorRequestCsPb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateActorRequestCsPb(CreateActorRequestCsPb other) : this() {
      _hasBits0 = other._hasBits0;
      actorName_ = other.actorName_;
      avatarSetting_ = other.avatarSetting_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateActorRequestCsPb Clone() {
      return new CreateActorRequestCsPb(this);
    }

    /// <summary>Field number for the "actorName" field.</summary>
    public const int ActorNameFieldNumber = 1;
    private string actorName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ActorName {
      get { return actorName_ ?? ""; }
      set {
        actorName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "actorName" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasActorName {
      get { return actorName_ != null; }
    }
    /// <summary>Clears the value of the "actorName" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearActorName() {
      actorName_ = null;
    }

    /// <summary>Field number for the "avatarSetting" field.</summary>
    public const int AvatarSettingFieldNumber = 2;
    private long avatarSetting_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AvatarSetting {
      get { if ((_hasBits0 & 1) != 0) { return avatarSetting_; } else { return 0L; } }
      set {
        _hasBits0 |= 1;
        avatarSetting_ = value;
      }
    }
    /// <summary>Gets whether the "avatarSetting" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAvatarSetting {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "avatarSetting" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAvatarSetting() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateActorRequestCsPb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateActorRequestCsPb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActorName != other.ActorName) return false;
      if (AvatarSetting != other.AvatarSetting) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasActorName) hash ^= ActorName.GetHashCode();
      if (HasAvatarSetting) hash ^= AvatarSetting.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasActorName) {
        output.WriteRawTag(10);
        output.WriteString(ActorName);
      }
      if (HasAvatarSetting) {
        output.WriteRawTag(16);
        output.WriteInt64(AvatarSetting);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasActorName) {
        output.WriteRawTag(10);
        output.WriteString(ActorName);
      }
      if (HasAvatarSetting) {
        output.WriteRawTag(16);
        output.WriteInt64(AvatarSetting);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasActorName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActorName);
      }
      if (HasAvatarSetting) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AvatarSetting);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateActorRequestCsPb other) {
      if (other == null) {
        return;
      }
      if (other.HasActorName) {
        ActorName = other.ActorName;
      }
      if (other.HasAvatarSetting) {
        AvatarSetting = other.AvatarSetting;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ActorName = input.ReadString();
            break;
          }
          case 16: {
            AvatarSetting = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ActorName = input.ReadString();
            break;
          }
          case 16: {
            AvatarSetting = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
