// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/WorldMessages/common/PetData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Net.Messages.Common {

  /// <summary>Holder for reflection information generated from protos/WorldMessages/common/PetData.proto</summary>
  public static partial class PetDataReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/WorldMessages/common/PetData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PetDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cilwcm90b3MvV29ybGRNZXNzYWdlcy9jb21tb24vUGV0RGF0YS5wcm90bxId",
            "TWV0YVZpcnVzLk5ldC5NZXNzYWdlcy5Db21tb24i1QEKCVBCUGV0RGF0YRIS",
            "CgVwZXRJZBgBIAEoBUgAiAEBEhYKCXBldERhdGFJZBgCIAEoBUgBiAEBEhwK",
            "D2NoYXJhY3RlckRhdGFJZBgDIAEoBUgCiAEBEhIKBWxldmVsGAQgASgFSAOI",
            "AQESEQoEbmFtZRgFIAEoCUgEiAEBEhAKA2V4cBgGIAEoBUgFiAEBQggKBl9w",
            "ZXRJZEIMCgpfcGV0RGF0YUlkQhIKEF9jaGFyYWN0ZXJEYXRhSWRCCAoGX2xl",
            "dmVsQgcKBV9uYW1lQgYKBF9leHBCNgokY29tLm1ldGF2aXJ1cy5uZXQubWVz",
            "c2FnZXMucGIuY29tbW9uQgxQZXREYXRhUGJPdXRQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Net.Messages.Common.PBPetData), global::MetaVirus.Net.Messages.Common.PBPetData.Parser, new[]{ "PetId", "PetDataId", "CharacterDataId", "Level", "Name", "Exp" }, new[]{ "PetId", "PetDataId", "CharacterDataId", "Level", "Name", "Exp" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PBPetData : pb::IMessage<PBPetData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBPetData> _parser = new pb::MessageParser<PBPetData>(() => new PBPetData());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBPetData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Net.Messages.Common.PetDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPetData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPetData(PBPetData other) : this() {
      _hasBits0 = other._hasBits0;
      petId_ = other.petId_;
      petDataId_ = other.petDataId_;
      characterDataId_ = other.characterDataId_;
      level_ = other.level_;
      name_ = other.name_;
      exp_ = other.exp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPetData Clone() {
      return new PBPetData(this);
    }

    /// <summary>Field number for the "petId" field.</summary>
    public const int PetIdFieldNumber = 1;
    private int petId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PetId {
      get { if ((_hasBits0 & 1) != 0) { return petId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        petId_ = value;
      }
    }
    /// <summary>Gets whether the "petId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPetId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "petId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPetId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "petDataId" field.</summary>
    public const int PetDataIdFieldNumber = 2;
    private int petDataId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PetDataId {
      get { if ((_hasBits0 & 2) != 0) { return petDataId_; } else { return 0; } }
      set {
        _hasBits0 |= 2;
        petDataId_ = value;
      }
    }
    /// <summary>Gets whether the "petDataId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPetDataId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "petDataId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPetDataId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "characterDataId" field.</summary>
    public const int CharacterDataIdFieldNumber = 3;
    private int characterDataId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CharacterDataId {
      get { if ((_hasBits0 & 4) != 0) { return characterDataId_; } else { return 0; } }
      set {
        _hasBits0 |= 4;
        characterDataId_ = value;
      }
    }
    /// <summary>Gets whether the "characterDataId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCharacterDataId {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "characterDataId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCharacterDataId() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 4;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { if ((_hasBits0 & 8) != 0) { return level_; } else { return 0; } }
      set {
        _hasBits0 |= 8;
        level_ = value;
      }
    }
    /// <summary>Gets whether the "level" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLevel {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "level" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLevel() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 5;
    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? ""; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 6;
    private int exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Exp {
      get { if ((_hasBits0 & 16) != 0) { return exp_; } else { return 0; } }
      set {
        _hasBits0 |= 16;
        exp_ = value;
      }
    }
    /// <summary>Gets whether the "exp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasExp {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "exp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearExp() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBPetData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBPetData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PetId != other.PetId) return false;
      if (PetDataId != other.PetDataId) return false;
      if (CharacterDataId != other.CharacterDataId) return false;
      if (Level != other.Level) return false;
      if (Name != other.Name) return false;
      if (Exp != other.Exp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPetId) hash ^= PetId.GetHashCode();
      if (HasPetDataId) hash ^= PetDataId.GetHashCode();
      if (HasCharacterDataId) hash ^= CharacterDataId.GetHashCode();
      if (HasLevel) hash ^= Level.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasExp) hash ^= Exp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPetId) {
        output.WriteRawTag(8);
        output.WriteInt32(PetId);
      }
      if (HasPetDataId) {
        output.WriteRawTag(16);
        output.WriteInt32(PetDataId);
      }
      if (HasCharacterDataId) {
        output.WriteRawTag(24);
        output.WriteInt32(CharacterDataId);
      }
      if (HasLevel) {
        output.WriteRawTag(32);
        output.WriteInt32(Level);
      }
      if (HasName) {
        output.WriteRawTag(42);
        output.WriteString(Name);
      }
      if (HasExp) {
        output.WriteRawTag(48);
        output.WriteInt32(Exp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPetId) {
        output.WriteRawTag(8);
        output.WriteInt32(PetId);
      }
      if (HasPetDataId) {
        output.WriteRawTag(16);
        output.WriteInt32(PetDataId);
      }
      if (HasCharacterDataId) {
        output.WriteRawTag(24);
        output.WriteInt32(CharacterDataId);
      }
      if (HasLevel) {
        output.WriteRawTag(32);
        output.WriteInt32(Level);
      }
      if (HasName) {
        output.WriteRawTag(42);
        output.WriteString(Name);
      }
      if (HasExp) {
        output.WriteRawTag(48);
        output.WriteInt32(Exp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPetId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PetId);
      }
      if (HasPetDataId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PetDataId);
      }
      if (HasCharacterDataId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CharacterDataId);
      }
      if (HasLevel) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasExp) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Exp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBPetData other) {
      if (other == null) {
        return;
      }
      if (other.HasPetId) {
        PetId = other.PetId;
      }
      if (other.HasPetDataId) {
        PetDataId = other.PetDataId;
      }
      if (other.HasCharacterDataId) {
        CharacterDataId = other.CharacterDataId;
      }
      if (other.HasLevel) {
        Level = other.Level;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasExp) {
        Exp = other.Exp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PetId = input.ReadInt32();
            break;
          }
          case 16: {
            PetDataId = input.ReadInt32();
            break;
          }
          case 24: {
            CharacterDataId = input.ReadInt32();
            break;
          }
          case 32: {
            Level = input.ReadInt32();
            break;
          }
          case 42: {
            Name = input.ReadString();
            break;
          }
          case 48: {
            Exp = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PetId = input.ReadInt32();
            break;
          }
          case 16: {
            PetDataId = input.ReadInt32();
            break;
          }
          case 24: {
            CharacterDataId = input.ReadInt32();
            break;
          }
          case 32: {
            Level = input.ReadInt32();
            break;
          }
          case 42: {
            Name = input.ReadString();
            break;
          }
          case 48: {
            Exp = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
