// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/WorldMessages/common/PlayerData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Net.Messages.Common {

  /// <summary>Holder for reflection information generated from protos/WorldMessages/common/PlayerData.proto</summary>
  public static partial class PlayerDataReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/WorldMessages/common/PlayerData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixwcm90b3MvV29ybGRNZXNzYWdlcy9jb21tb24vUGxheWVyRGF0YS5wcm90",
            "bxIdTWV0YVZpcnVzLk5ldC5NZXNzYWdlcy5Db21tb24aKXByb3Rvcy9Xb3Js",
            "ZE1lc3NhZ2VzL2NvbW1vbi92ZWN0b3IzLnByb3RvGjFwcm90b3MvV29ybGRN",
            "ZXNzYWdlcy9jb21tb24vUEJGb3JtYXRpb25EYXRhLnByb3RvIpoECgxQQlBs",
            "YXllckRhdGESFQoIcGxheWVySWQYASABKAVIAIgBARIWCglhY2NvdW50SWQY",
            "AiABKANIAYgBARISCgVtYXBJZBgDIAEoBUgCiAEBEhQKB2xheWVySWQYBCAB",
            "KAVIA4gBARI/Cghwb3NpdGlvbhgFIAEoCzIoLk1ldGFWaXJ1cy5OZXQuTWVz",
            "c2FnZXMuQ29tbW9uLlBCVmVjdG9yM0gEiAEBEhUKCHJvdGF0aW9uGAYgASgC",
            "SAWIAQESEwoGZ2VuZGVyGAcgASgFSAaIAQESEgoFbGV2ZWwYCCABKAVIB4gB",
            "ARIRCgRuYW1lGAkgASgJSAiIAQESEAoDZXhwGAogASgFSAmIAQESQgoKZm9y",
            "bWF0aW9ucxgLIAMoCzIuLk1ldGFWaXJ1cy5OZXQuTWVzc2FnZXMuQ29tbW9u",
            "LlBCRm9ybWF0aW9uRGF0YRIYCgthdHRhY2tQYXJ0eRgMIAEoBUgKiAEBEhoK",
            "DWF2YXRhclNldHRpbmcYDSABKANIC4gBAUILCglfcGxheWVySWRCDAoKX2Fj",
            "Y291bnRJZEIICgZfbWFwSWRCCgoIX2xheWVySWRCCwoJX3Bvc2l0aW9uQgsK",
            "CV9yb3RhdGlvbkIJCgdfZ2VuZGVyQggKBl9sZXZlbEIHCgVfbmFtZUIGCgRf",
            "ZXhwQg4KDF9hdHRhY2tQYXJ0eUIQCg5fYXZhdGFyU2V0dGluZ0I5CiRjb20u",
            "bWV0YXZpcnVzLm5ldC5tZXNzYWdlcy5wYi5jb21tb25CD1BsYXllckRhdGFQ",
            "Yk91dFABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MetaVirus.Net.Messages.Common.Vector3Reflection.Descriptor, global::MetaVirus.Net.Messages.Common.PBFormationDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Net.Messages.Common.PBPlayerData), global::MetaVirus.Net.Messages.Common.PBPlayerData.Parser, new[]{ "PlayerId", "AccountId", "MapId", "LayerId", "Position", "Rotation", "Gender", "Level", "Name", "Exp", "Formations", "AttackParty", "AvatarSetting" }, new[]{ "PlayerId", "AccountId", "MapId", "LayerId", "Position", "Rotation", "Gender", "Level", "Name", "Exp", "AttackParty", "AvatarSetting" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PBPlayerData : pb::IMessage<PBPlayerData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBPlayerData> _parser = new pb::MessageParser<PBPlayerData>(() => new PBPlayerData());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBPlayerData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Net.Messages.Common.PlayerDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPlayerData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPlayerData(PBPlayerData other) : this() {
      _hasBits0 = other._hasBits0;
      playerId_ = other.playerId_;
      accountId_ = other.accountId_;
      mapId_ = other.mapId_;
      layerId_ = other.layerId_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      rotation_ = other.rotation_;
      gender_ = other.gender_;
      level_ = other.level_;
      name_ = other.name_;
      exp_ = other.exp_;
      formations_ = other.formations_.Clone();
      attackParty_ = other.attackParty_;
      avatarSetting_ = other.avatarSetting_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBPlayerData Clone() {
      return new PBPlayerData(this);
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private int playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PlayerId {
      get { if ((_hasBits0 & 1) != 0) { return playerId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        playerId_ = value;
      }
    }
    /// <summary>Gets whether the "playerId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPlayerId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "playerId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPlayerId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "accountId" field.</summary>
    public const int AccountIdFieldNumber = 2;
    private long accountId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AccountId {
      get { if ((_hasBits0 & 2) != 0) { return accountId_; } else { return 0L; } }
      set {
        _hasBits0 |= 2;
        accountId_ = value;
      }
    }
    /// <summary>Gets whether the "accountId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAccountId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "accountId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAccountId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "mapId" field.</summary>
    public const int MapIdFieldNumber = 3;
    private int mapId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MapId {
      get { if ((_hasBits0 & 4) != 0) { return mapId_; } else { return 0; } }
      set {
        _hasBits0 |= 4;
        mapId_ = value;
      }
    }
    /// <summary>Gets whether the "mapId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMapId {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "mapId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMapId() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "layerId" field.</summary>
    public const int LayerIdFieldNumber = 4;
    private int layerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LayerId {
      get { if ((_hasBits0 & 8) != 0) { return layerId_; } else { return 0; } }
      set {
        _hasBits0 |= 8;
        layerId_ = value;
      }
    }
    /// <summary>Gets whether the "layerId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLayerId {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "layerId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLayerId() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 5;
    private global::MetaVirus.Net.Messages.Common.PBVector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MetaVirus.Net.Messages.Common.PBVector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 6;
    private float rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Rotation {
      get { if ((_hasBits0 & 16) != 0) { return rotation_; } else { return 0F; } }
      set {
        _hasBits0 |= 16;
        rotation_ = value;
      }
    }
    /// <summary>Gets whether the "rotation" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRotation {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "rotation" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRotation() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 7;
    private int gender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Gender {
      get { if ((_hasBits0 & 32) != 0) { return gender_; } else { return 0; } }
      set {
        _hasBits0 |= 32;
        gender_ = value;
      }
    }
    /// <summary>Gets whether the "gender" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGender {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "gender" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGender() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 8;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { if ((_hasBits0 & 64) != 0) { return level_; } else { return 0; } }
      set {
        _hasBits0 |= 64;
        level_ = value;
      }
    }
    /// <summary>Gets whether the "level" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLevel {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "level" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLevel() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 9;
    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? ""; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 10;
    private int exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Exp {
      get { if ((_hasBits0 & 128) != 0) { return exp_; } else { return 0; } }
      set {
        _hasBits0 |= 128;
        exp_ = value;
      }
    }
    /// <summary>Gets whether the "exp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasExp {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "exp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearExp() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "formations" field.</summary>
    public const int FormationsFieldNumber = 11;
    private static readonly pb::FieldCodec<global::MetaVirus.Net.Messages.Common.PBFormationData> _repeated_formations_codec
        = pb::FieldCodec.ForMessage(90, global::MetaVirus.Net.Messages.Common.PBFormationData.Parser);
    private readonly pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBFormationData> formations_ = new pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBFormationData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBFormationData> Formations {
      get { return formations_; }
    }

    /// <summary>Field number for the "attackParty" field.</summary>
    public const int AttackPartyFieldNumber = 12;
    private int attackParty_;
    /// <summary>
    ///战斗用小队Id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AttackParty {
      get { if ((_hasBits0 & 256) != 0) { return attackParty_; } else { return 0; } }
      set {
        _hasBits0 |= 256;
        attackParty_ = value;
      }
    }
    /// <summary>Gets whether the "attackParty" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAttackParty {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "attackParty" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAttackParty() {
      _hasBits0 &= ~256;
    }

    /// <summary>Field number for the "avatarSetting" field.</summary>
    public const int AvatarSettingFieldNumber = 13;
    private long avatarSetting_;
    /// <summary>
    ///avatar setting
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AvatarSetting {
      get { if ((_hasBits0 & 512) != 0) { return avatarSetting_; } else { return 0L; } }
      set {
        _hasBits0 |= 512;
        avatarSetting_ = value;
      }
    }
    /// <summary>Gets whether the "avatarSetting" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAvatarSetting {
      get { return (_hasBits0 & 512) != 0; }
    }
    /// <summary>Clears the value of the "avatarSetting" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAvatarSetting() {
      _hasBits0 &= ~512;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBPlayerData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBPlayerData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if (AccountId != other.AccountId) return false;
      if (MapId != other.MapId) return false;
      if (LayerId != other.LayerId) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Rotation, other.Rotation)) return false;
      if (Gender != other.Gender) return false;
      if (Level != other.Level) return false;
      if (Name != other.Name) return false;
      if (Exp != other.Exp) return false;
      if(!formations_.Equals(other.formations_)) return false;
      if (AttackParty != other.AttackParty) return false;
      if (AvatarSetting != other.AvatarSetting) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPlayerId) hash ^= PlayerId.GetHashCode();
      if (HasAccountId) hash ^= AccountId.GetHashCode();
      if (HasMapId) hash ^= MapId.GetHashCode();
      if (HasLayerId) hash ^= LayerId.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (HasRotation) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Rotation);
      if (HasGender) hash ^= Gender.GetHashCode();
      if (HasLevel) hash ^= Level.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasExp) hash ^= Exp.GetHashCode();
      hash ^= formations_.GetHashCode();
      if (HasAttackParty) hash ^= AttackParty.GetHashCode();
      if (HasAvatarSetting) hash ^= AvatarSetting.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPlayerId) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerId);
      }
      if (HasAccountId) {
        output.WriteRawTag(16);
        output.WriteInt64(AccountId);
      }
      if (HasMapId) {
        output.WriteRawTag(24);
        output.WriteInt32(MapId);
      }
      if (HasLayerId) {
        output.WriteRawTag(32);
        output.WriteInt32(LayerId);
      }
      if (position_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Position);
      }
      if (HasRotation) {
        output.WriteRawTag(53);
        output.WriteFloat(Rotation);
      }
      if (HasGender) {
        output.WriteRawTag(56);
        output.WriteInt32(Gender);
      }
      if (HasLevel) {
        output.WriteRawTag(64);
        output.WriteInt32(Level);
      }
      if (HasName) {
        output.WriteRawTag(74);
        output.WriteString(Name);
      }
      if (HasExp) {
        output.WriteRawTag(80);
        output.WriteInt32(Exp);
      }
      formations_.WriteTo(output, _repeated_formations_codec);
      if (HasAttackParty) {
        output.WriteRawTag(96);
        output.WriteInt32(AttackParty);
      }
      if (HasAvatarSetting) {
        output.WriteRawTag(104);
        output.WriteInt64(AvatarSetting);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPlayerId) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerId);
      }
      if (HasAccountId) {
        output.WriteRawTag(16);
        output.WriteInt64(AccountId);
      }
      if (HasMapId) {
        output.WriteRawTag(24);
        output.WriteInt32(MapId);
      }
      if (HasLayerId) {
        output.WriteRawTag(32);
        output.WriteInt32(LayerId);
      }
      if (position_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Position);
      }
      if (HasRotation) {
        output.WriteRawTag(53);
        output.WriteFloat(Rotation);
      }
      if (HasGender) {
        output.WriteRawTag(56);
        output.WriteInt32(Gender);
      }
      if (HasLevel) {
        output.WriteRawTag(64);
        output.WriteInt32(Level);
      }
      if (HasName) {
        output.WriteRawTag(74);
        output.WriteString(Name);
      }
      if (HasExp) {
        output.WriteRawTag(80);
        output.WriteInt32(Exp);
      }
      formations_.WriteTo(ref output, _repeated_formations_codec);
      if (HasAttackParty) {
        output.WriteRawTag(96);
        output.WriteInt32(AttackParty);
      }
      if (HasAvatarSetting) {
        output.WriteRawTag(104);
        output.WriteInt64(AvatarSetting);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPlayerId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerId);
      }
      if (HasAccountId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AccountId);
      }
      if (HasMapId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MapId);
      }
      if (HasLayerId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LayerId);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (HasRotation) {
        size += 1 + 4;
      }
      if (HasGender) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gender);
      }
      if (HasLevel) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasExp) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Exp);
      }
      size += formations_.CalculateSize(_repeated_formations_codec);
      if (HasAttackParty) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttackParty);
      }
      if (HasAvatarSetting) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AvatarSetting);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBPlayerData other) {
      if (other == null) {
        return;
      }
      if (other.HasPlayerId) {
        PlayerId = other.PlayerId;
      }
      if (other.HasAccountId) {
        AccountId = other.AccountId;
      }
      if (other.HasMapId) {
        MapId = other.MapId;
      }
      if (other.HasLayerId) {
        LayerId = other.LayerId;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::MetaVirus.Net.Messages.Common.PBVector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.HasRotation) {
        Rotation = other.Rotation;
      }
      if (other.HasGender) {
        Gender = other.Gender;
      }
      if (other.HasLevel) {
        Level = other.Level;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasExp) {
        Exp = other.Exp;
      }
      formations_.Add(other.formations_);
      if (other.HasAttackParty) {
        AttackParty = other.AttackParty;
      }
      if (other.HasAvatarSetting) {
        AvatarSetting = other.AvatarSetting;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerId = input.ReadInt32();
            break;
          }
          case 16: {
            AccountId = input.ReadInt64();
            break;
          }
          case 24: {
            MapId = input.ReadInt32();
            break;
          }
          case 32: {
            LayerId = input.ReadInt32();
            break;
          }
          case 42: {
            if (position_ == null) {
              Position = new global::MetaVirus.Net.Messages.Common.PBVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 53: {
            Rotation = input.ReadFloat();
            break;
          }
          case 56: {
            Gender = input.ReadInt32();
            break;
          }
          case 64: {
            Level = input.ReadInt32();
            break;
          }
          case 74: {
            Name = input.ReadString();
            break;
          }
          case 80: {
            Exp = input.ReadInt32();
            break;
          }
          case 90: {
            formations_.AddEntriesFrom(input, _repeated_formations_codec);
            break;
          }
          case 96: {
            AttackParty = input.ReadInt32();
            break;
          }
          case 104: {
            AvatarSetting = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerId = input.ReadInt32();
            break;
          }
          case 16: {
            AccountId = input.ReadInt64();
            break;
          }
          case 24: {
            MapId = input.ReadInt32();
            break;
          }
          case 32: {
            LayerId = input.ReadInt32();
            break;
          }
          case 42: {
            if (position_ == null) {
              Position = new global::MetaVirus.Net.Messages.Common.PBVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 53: {
            Rotation = input.ReadFloat();
            break;
          }
          case 56: {
            Gender = input.ReadInt32();
            break;
          }
          case 64: {
            Level = input.ReadInt32();
            break;
          }
          case 74: {
            Name = input.ReadString();
            break;
          }
          case 80: {
            Exp = input.ReadInt32();
            break;
          }
          case 90: {
            formations_.AddEntriesFrom(ref input, _repeated_formations_codec);
            break;
          }
          case 96: {
            AttackParty = input.ReadInt32();
            break;
          }
          case 104: {
            AvatarSetting = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
