// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WorldMessages/scene/SC_NotifyGridItemsMove.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Net.Messages.Scene {

  /// <summary>Holder for reflection information generated from WorldMessages/scene/SC_NotifyGridItemsMove.proto</summary>
  public static partial class SCNotifyGridItemsMoveReflection {

    #region Descriptor
    /// <summary>File descriptor for WorldMessages/scene/SC_NotifyGridItemsMove.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SCNotifyGridItemsMoveReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjBXb3JsZE1lc3NhZ2VzL3NjZW5lL1NDX05vdGlmeUdyaWRJdGVtc01vdmUu",
            "cHJvdG8SHE1ldGFWaXJ1cy5OZXQuTWVzc2FnZXMuU2NlbmUaKnByb3Rvcy9X",
            "b3JsZE1lc3NhZ2VzL2NvbW1vbi9HcmlkSXRlbS5wcm90byJYChhTQ19Ob3Rp",
            "ZnlHcmlkSXRlbXNNb3ZlUGISPAoJZ3JpZEl0ZW1zGAEgAygLMikuTWV0YVZp",
            "cnVzLk5ldC5NZXNzYWdlcy5Db21tb24uUEJHcmlkSXRlbUJECiNjb20ubWV0",
            "YXZpcnVzLm5ldC5tZXNzYWdlcy5wYi5zY2VuZUIbU0NfTm90aWZ5R3JpZEl0",
            "ZW1zTW92ZVBiT3V0UAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MetaVirus.Net.Messages.Common.GridItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Net.Messages.Scene.SC_NotifyGridItemsMovePb), global::MetaVirus.Net.Messages.Scene.SC_NotifyGridItemsMovePb.Parser, new[]{ "GridItems" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SC_NotifyGridItemsMovePb : pb::IMessage<SC_NotifyGridItemsMovePb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SC_NotifyGridItemsMovePb> _parser = new pb::MessageParser<SC_NotifyGridItemsMovePb>(() => new SC_NotifyGridItemsMovePb());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SC_NotifyGridItemsMovePb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Net.Messages.Scene.SCNotifyGridItemsMoveReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC_NotifyGridItemsMovePb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC_NotifyGridItemsMovePb(SC_NotifyGridItemsMovePb other) : this() {
      gridItems_ = other.gridItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC_NotifyGridItemsMovePb Clone() {
      return new SC_NotifyGridItemsMovePb(this);
    }

    /// <summary>Field number for the "gridItems" field.</summary>
    public const int GridItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MetaVirus.Net.Messages.Common.PBGridItem> _repeated_gridItems_codec
        = pb::FieldCodec.ForMessage(10, global::MetaVirus.Net.Messages.Common.PBGridItem.Parser);
    private readonly pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBGridItem> gridItems_ = new pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBGridItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBGridItem> GridItems {
      get { return gridItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SC_NotifyGridItemsMovePb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SC_NotifyGridItemsMovePb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!gridItems_.Equals(other.gridItems_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= gridItems_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      gridItems_.WriteTo(output, _repeated_gridItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      gridItems_.WriteTo(ref output, _repeated_gridItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += gridItems_.CalculateSize(_repeated_gridItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SC_NotifyGridItemsMovePb other) {
      if (other == null) {
        return;
      }
      gridItems_.Add(other.gridItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            gridItems_.AddEntriesFrom(input, _repeated_gridItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            gridItems_.AddEntriesFrom(ref input, _repeated_gridItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
