// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WorldMessages/testpb/TestCreateMonsterResponseSCPb.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Net.Messages.Test {

  /// <summary>Holder for reflection information generated from WorldMessages/testpb/TestCreateMonsterResponseSCPb.proto</summary>
  public static partial class TestCreateMonsterResponseSCPbReflection {

    #region Descriptor
    /// <summary>File descriptor for WorldMessages/testpb/TestCreateMonsterResponseSCPb.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestCreateMonsterResponseSCPbReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhXb3JsZE1lc3NhZ2VzL3Rlc3RwYi9UZXN0Q3JlYXRlTW9uc3RlclJlc3Bv",
            "bnNlU0NQYi5wcm90bxIbTWV0YVZpcnVzLk5ldC5NZXNzYWdlcy5UZXN0Gilw",
            "cm90b3MvV29ybGRNZXNzYWdlcy9jb21tb24vUGV0RGF0YS5wcm90byKJAQod",
            "VGVzdENyZWF0ZU1vbnN0ZXJSZXNwb25zZVNDUGISEgoFcGV0SWQYASABKAVI",
            "AIgBARI+CgdwZXREYXRhGAIgASgLMiguTWV0YVZpcnVzLk5ldC5NZXNzYWdl",
            "cy5Db21tb24uUEJQZXREYXRhSAGIAQFCCAoGX3BldElkQgoKCF9wZXREYXRh",
            "QkgKImNvbS5tZXRhdmlydXMubmV0Lm1lc3NhZ2VzLnBiLnRlc3RCIFRlc3RD",
            "cmVhdGVNb25zdGVyUmVzcG9uc2VTQ1BiT3V0UAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MetaVirus.Net.Messages.Common.PetDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Net.Messages.Test.TestCreateMonsterResponseSCPb), global::MetaVirus.Net.Messages.Test.TestCreateMonsterResponseSCPb.Parser, new[]{ "PetId", "PetData" }, new[]{ "PetId", "PetData" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TestCreateMonsterResponseSCPb : pb::IMessage<TestCreateMonsterResponseSCPb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestCreateMonsterResponseSCPb> _parser = new pb::MessageParser<TestCreateMonsterResponseSCPb>(() => new TestCreateMonsterResponseSCPb());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestCreateMonsterResponseSCPb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Net.Messages.Test.TestCreateMonsterResponseSCPbReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestCreateMonsterResponseSCPb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestCreateMonsterResponseSCPb(TestCreateMonsterResponseSCPb other) : this() {
      _hasBits0 = other._hasBits0;
      petId_ = other.petId_;
      petData_ = other.petData_ != null ? other.petData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestCreateMonsterResponseSCPb Clone() {
      return new TestCreateMonsterResponseSCPb(this);
    }

    /// <summary>Field number for the "petId" field.</summary>
    public const int PetIdFieldNumber = 1;
    private int petId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PetId {
      get { if ((_hasBits0 & 1) != 0) { return petId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        petId_ = value;
      }
    }
    /// <summary>Gets whether the "petId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPetId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "petId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPetId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "petData" field.</summary>
    public const int PetDataFieldNumber = 2;
    private global::MetaVirus.Net.Messages.Common.PBPetData petData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MetaVirus.Net.Messages.Common.PBPetData PetData {
      get { return petData_; }
      set {
        petData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestCreateMonsterResponseSCPb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestCreateMonsterResponseSCPb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PetId != other.PetId) return false;
      if (!object.Equals(PetData, other.PetData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPetId) hash ^= PetId.GetHashCode();
      if (petData_ != null) hash ^= PetData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPetId) {
        output.WriteRawTag(8);
        output.WriteInt32(PetId);
      }
      if (petData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PetData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPetId) {
        output.WriteRawTag(8);
        output.WriteInt32(PetId);
      }
      if (petData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PetData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPetId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PetId);
      }
      if (petData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PetData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestCreateMonsterResponseSCPb other) {
      if (other == null) {
        return;
      }
      if (other.HasPetId) {
        PetId = other.PetId;
      }
      if (other.petData_ != null) {
        if (petData_ == null) {
          PetData = new global::MetaVirus.Net.Messages.Common.PBPetData();
        }
        PetData.MergeFrom(other.PetData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PetId = input.ReadInt32();
            break;
          }
          case 18: {
            if (petData_ == null) {
              PetData = new global::MetaVirus.Net.Messages.Common.PBPetData();
            }
            input.ReadMessage(PetData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PetId = input.ReadInt32();
            break;
          }
          case 18: {
            if (petData_ == null) {
              PetData = new global::MetaVirus.Net.Messages.Common.PBPetData();
            }
            input.ReadMessage(PetData);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
