// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WorldMessages/scene/TouchNpcResponseSc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Net.Messages.Scene {

  /// <summary>Holder for reflection information generated from WorldMessages/scene/TouchNpcResponseSc.proto</summary>
  public static partial class TouchNpcResponseScReflection {

    #region Descriptor
    /// <summary>File descriptor for WorldMessages/scene/TouchNpcResponseSc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TouchNpcResponseScReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixXb3JsZE1lc3NhZ2VzL3NjZW5lL1RvdWNoTnBjUmVzcG9uc2VTYy5wcm90",
            "bxIcTWV0YVZpcnVzLk5ldC5NZXNzYWdlcy5TY2VuZRoxcHJvdG9zL1dvcmxk",
            "TWVzc2FnZXMvY29tbW9uL05wY0Z1bmN0aW9uSXRlbS5wcm90byKdAQoUVG91",
            "Y2hOcGNSZXNwb25zZVNDUGISEgoFbnBjSWQYASABKAVIAIgBARIVCghncmVl",
            "dGluZxgCIAEoCUgBiAEBEkMKCWZ1bmNJdGVtcxgDIAMoCzIwLk1ldGFWaXJ1",
            "cy5OZXQuTWVzc2FnZXMuQ29tbW9uLlBCTnBjRnVuY3Rpb25JdGVtQggKBl9u",
            "cGNJZEILCglfZ3JlZXRpbmdCQAojY29tLm1ldGF2aXJ1cy5uZXQubWVzc2Fn",
            "ZXMucGIuc2NlbmVCF1RvdWNoTnBjUmVzcG9uc2VTQ1BiT3V0UAFiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MetaVirus.Net.Messages.Common.NpcFunctionItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Net.Messages.Scene.TouchNpcResponseSCPb), global::MetaVirus.Net.Messages.Scene.TouchNpcResponseSCPb.Parser, new[]{ "NpcId", "Greeting", "FuncItems" }, new[]{ "NpcId", "Greeting" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TouchNpcResponseSCPb : pb::IMessage<TouchNpcResponseSCPb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TouchNpcResponseSCPb> _parser = new pb::MessageParser<TouchNpcResponseSCPb>(() => new TouchNpcResponseSCPb());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TouchNpcResponseSCPb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Net.Messages.Scene.TouchNpcResponseScReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TouchNpcResponseSCPb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TouchNpcResponseSCPb(TouchNpcResponseSCPb other) : this() {
      _hasBits0 = other._hasBits0;
      npcId_ = other.npcId_;
      greeting_ = other.greeting_;
      funcItems_ = other.funcItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TouchNpcResponseSCPb Clone() {
      return new TouchNpcResponseSCPb(this);
    }

    /// <summary>Field number for the "npcId" field.</summary>
    public const int NpcIdFieldNumber = 1;
    private int npcId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NpcId {
      get { if ((_hasBits0 & 1) != 0) { return npcId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        npcId_ = value;
      }
    }
    /// <summary>Gets whether the "npcId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNpcId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "npcId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNpcId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "greeting" field.</summary>
    public const int GreetingFieldNumber = 2;
    private string greeting_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Greeting {
      get { return greeting_ ?? ""; }
      set {
        greeting_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "greeting" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGreeting {
      get { return greeting_ != null; }
    }
    /// <summary>Clears the value of the "greeting" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGreeting() {
      greeting_ = null;
    }

    /// <summary>Field number for the "funcItems" field.</summary>
    public const int FuncItemsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::MetaVirus.Net.Messages.Common.PBNpcFunctionItem> _repeated_funcItems_codec
        = pb::FieldCodec.ForMessage(26, global::MetaVirus.Net.Messages.Common.PBNpcFunctionItem.Parser);
    private readonly pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBNpcFunctionItem> funcItems_ = new pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBNpcFunctionItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBNpcFunctionItem> FuncItems {
      get { return funcItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TouchNpcResponseSCPb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TouchNpcResponseSCPb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NpcId != other.NpcId) return false;
      if (Greeting != other.Greeting) return false;
      if(!funcItems_.Equals(other.funcItems_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasNpcId) hash ^= NpcId.GetHashCode();
      if (HasGreeting) hash ^= Greeting.GetHashCode();
      hash ^= funcItems_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasNpcId) {
        output.WriteRawTag(8);
        output.WriteInt32(NpcId);
      }
      if (HasGreeting) {
        output.WriteRawTag(18);
        output.WriteString(Greeting);
      }
      funcItems_.WriteTo(output, _repeated_funcItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasNpcId) {
        output.WriteRawTag(8);
        output.WriteInt32(NpcId);
      }
      if (HasGreeting) {
        output.WriteRawTag(18);
        output.WriteString(Greeting);
      }
      funcItems_.WriteTo(ref output, _repeated_funcItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasNpcId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NpcId);
      }
      if (HasGreeting) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Greeting);
      }
      size += funcItems_.CalculateSize(_repeated_funcItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TouchNpcResponseSCPb other) {
      if (other == null) {
        return;
      }
      if (other.HasNpcId) {
        NpcId = other.NpcId;
      }
      if (other.HasGreeting) {
        Greeting = other.Greeting;
      }
      funcItems_.Add(other.funcItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NpcId = input.ReadInt32();
            break;
          }
          case 18: {
            Greeting = input.ReadString();
            break;
          }
          case 26: {
            funcItems_.AddEntriesFrom(input, _repeated_funcItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            NpcId = input.ReadInt32();
            break;
          }
          case 18: {
            Greeting = input.ReadString();
            break;
          }
          case 26: {
            funcItems_.AddEntriesFrom(ref input, _repeated_funcItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
