// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WorldMessages/player/UpdateFormationRequestCs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaVirus.Net.Messages.Player {

  /// <summary>Holder for reflection information generated from WorldMessages/player/UpdateFormationRequestCs.proto</summary>
  public static partial class UpdateFormationRequestCsReflection {

    #region Descriptor
    /// <summary>File descriptor for WorldMessages/player/UpdateFormationRequestCs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UpdateFormationRequestCsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNXb3JsZE1lc3NhZ2VzL3BsYXllci9VcGRhdGVGb3JtYXRpb25SZXF1ZXN0",
            "Q3MucHJvdG8SHU1ldGFWaXJ1cy5OZXQuTWVzc2FnZXMuUGxheWVyGjFwcm90",
            "b3MvV29ybGRNZXNzYWdlcy9jb21tb24vUEJGb3JtYXRpb25EYXRhLnByb3Rv",
            "IpIBChpVcGRhdGVGb3JtYXRpb25SZXF1ZXN0Q3NQYhJCCgpmb3JtYXRpb25z",
            "GAEgAygLMi4uTWV0YVZpcnVzLk5ldC5NZXNzYWdlcy5Db21tb24uUEJGb3Jt",
            "YXRpb25EYXRhEhwKD2F0dGFja0Zvcm1hdGlvbhgCIAEoBUgAiAEBQhIKEF9h",
            "dHRhY2tGb3JtYXRpb25CRwokY29tLm1ldGF2aXJ1cy5uZXQubWVzc2FnZXMu",
            "cGIucGxheWVyQh1VcGRhdGVGb3JtYXRpb25SZXF1ZXN0Q3NQYk91dFABYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MetaVirus.Net.Messages.Common.PBFormationDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaVirus.Net.Messages.Player.UpdateFormationRequestCsPb), global::MetaVirus.Net.Messages.Player.UpdateFormationRequestCsPb.Parser, new[]{ "Formations", "AttackFormation" }, new[]{ "AttackFormation" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UpdateFormationRequestCsPb : pb::IMessage<UpdateFormationRequestCsPb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateFormationRequestCsPb> _parser = new pb::MessageParser<UpdateFormationRequestCsPb>(() => new UpdateFormationRequestCsPb());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateFormationRequestCsPb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaVirus.Net.Messages.Player.UpdateFormationRequestCsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateFormationRequestCsPb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateFormationRequestCsPb(UpdateFormationRequestCsPb other) : this() {
      _hasBits0 = other._hasBits0;
      formations_ = other.formations_.Clone();
      attackFormation_ = other.attackFormation_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateFormationRequestCsPb Clone() {
      return new UpdateFormationRequestCsPb(this);
    }

    /// <summary>Field number for the "formations" field.</summary>
    public const int FormationsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MetaVirus.Net.Messages.Common.PBFormationData> _repeated_formations_codec
        = pb::FieldCodec.ForMessage(10, global::MetaVirus.Net.Messages.Common.PBFormationData.Parser);
    private readonly pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBFormationData> formations_ = new pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBFormationData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MetaVirus.Net.Messages.Common.PBFormationData> Formations {
      get { return formations_; }
    }

    /// <summary>Field number for the "attackFormation" field.</summary>
    public const int AttackFormationFieldNumber = 2;
    private int attackFormation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AttackFormation {
      get { if ((_hasBits0 & 1) != 0) { return attackFormation_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        attackFormation_ = value;
      }
    }
    /// <summary>Gets whether the "attackFormation" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAttackFormation {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "attackFormation" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAttackFormation() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateFormationRequestCsPb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateFormationRequestCsPb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!formations_.Equals(other.formations_)) return false;
      if (AttackFormation != other.AttackFormation) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= formations_.GetHashCode();
      if (HasAttackFormation) hash ^= AttackFormation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      formations_.WriteTo(output, _repeated_formations_codec);
      if (HasAttackFormation) {
        output.WriteRawTag(16);
        output.WriteInt32(AttackFormation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      formations_.WriteTo(ref output, _repeated_formations_codec);
      if (HasAttackFormation) {
        output.WriteRawTag(16);
        output.WriteInt32(AttackFormation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += formations_.CalculateSize(_repeated_formations_codec);
      if (HasAttackFormation) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttackFormation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateFormationRequestCsPb other) {
      if (other == null) {
        return;
      }
      formations_.Add(other.formations_);
      if (other.HasAttackFormation) {
        AttackFormation = other.AttackFormation;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            formations_.AddEntriesFrom(input, _repeated_formations_codec);
            break;
          }
          case 16: {
            AttackFormation = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            formations_.AddEntriesFrom(ref input, _repeated_formations_codec);
            break;
          }
          case 16: {
            AttackFormation = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
