//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.item
{
    /// <summary>
    /// 物品类型
    /// </summary>
    public enum GameItemType
    {
        /// <summary>
        /// 杂物
        /// </summary>
        Miscellaneous = 1,
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumable = 2,
        /// <summary>
        /// 宝箱
        /// </summary>
        Treasure = 3,
        /// <summary>
        /// 宠物蛋
        /// </summary>
        MonsterEgg = 4,
        /// <summary>
        /// 装备
        /// </summary>
        Equipment = 5,
        /// <summary>
        /// 交易品
        /// </summary>
        TradeGoods = 6,
        /// <summary>
        /// 任务物品
        /// </summary>
        Quest = 7,
    }
}
