//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.battle
{
   
/// <summary>
/// Buff，Debuff配置表
/// </summary>
public partial class BuffDatas
{
    private readonly Dictionary<int, battle.BuffData> _dataMap;
    private readonly List<battle.BuffData> _dataList;
    
    public BuffDatas(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, battle.BuffData>();
        _dataList = new List<battle.BuffData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            battle.BuffData _v;
            _v = battle.BuffData.DeserializeBuffData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, battle.BuffData> DataMap => _dataMap;
    public List<battle.BuffData> DataList => _dataList;

    public battle.BuffData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public battle.BuffData Get(int key) => _dataMap[key];
    public battle.BuffData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}