//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.battle
{
   
/// <summary>
/// 怪物性格配置表
/// </summary>
public partial class CharacterDatas
{
    private readonly Dictionary<int, battle.CharacterData> _dataMap;
    private readonly List<battle.CharacterData> _dataList;
    
    public CharacterDatas(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, battle.CharacterData>();
        _dataList = new List<battle.CharacterData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            battle.CharacterData _v;
            _v = battle.CharacterData.DeserializeCharacterData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, battle.CharacterData> DataMap => _dataMap;
    public List<battle.CharacterData> DataList => _dataList;

    public battle.CharacterData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public battle.CharacterData Get(int key) => _dataMap[key];
    public battle.CharacterData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}