//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.battle
{
   
/// <summary>
/// 怪物属性配置表
/// </summary>
public partial class MonsterDatas
{
    private readonly Dictionary<int, battle.MonsterData> _dataMap;
    private readonly List<battle.MonsterData> _dataList;
    
    public MonsterDatas(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, battle.MonsterData>();
        _dataList = new List<battle.MonsterData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            battle.MonsterData _v;
            _v = battle.MonsterData.DeserializeMonsterData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, battle.MonsterData> DataMap => _dataMap;
    public List<battle.MonsterData> DataList => _dataList;

    public battle.MonsterData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public battle.MonsterData Get(int key) => _dataMap[key];
    public battle.MonsterData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}