//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.arena
{
   
/// <summary>
/// 竞技场配置数据
/// </summary>
public partial class ArenaDatas
{
    private readonly Dictionary<int, arena.ArenaData> _dataMap;
    private readonly List<arena.ArenaData> _dataList;
    
    public ArenaDatas(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, arena.ArenaData>();
        _dataList = new List<arena.ArenaData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            arena.ArenaData _v;
            _v = arena.ArenaData.DeserializeArenaData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, arena.ArenaData> DataMap => _dataMap;
    public List<arena.ArenaData> DataList => _dataList;

    public arena.ArenaData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public arena.ArenaData Get(int key) => _dataMap[key];
    public arena.ArenaData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}