//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.arena
{
    /// <summary>
    /// 竞技场赛季周期
    /// </summary>
    public enum ArenaSeasonCycleType
    {
        /// <summary>
        /// 每周
        /// </summary>
        Weekly = 1,
        /// <summary>
        /// 每月
        /// </summary>
        Monthly = 2,
        /// <summary>
        /// 每季度
        /// </summary>
        Quarterly = 3,
        /// <summary>
        /// 每年
        /// </summary>
        Yearly = 4,
    }
}
