//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.map
{
   
/// <summary>
/// 地图数据
/// </summary>
public partial class MapDatas
{
    private readonly Dictionary<int, map.MapData> _dataMap;
    private readonly List<map.MapData> _dataList;
    
    public MapDatas(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, map.MapData>();
        _dataList = new List<map.MapData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            map.MapData _v;
            _v = map.MapData.DeserializeMapData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, map.MapData> DataMap => _dataMap;
    public List<map.MapData> DataList => _dataList;

    public map.MapData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public map.MapData Get(int key) => _dataMap[key];
    public map.MapData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}