//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.buff
{
    /// <summary>
    /// Buff类型
    /// </summary>
    public enum BuffType
    {
        Buff = 1,
        Debuff = 2,
    }
}
