//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.attr
{
   
/// <summary>
/// 经验表
/// </summary>
public partial class LevelUpTables
{
    private readonly Dictionary<int, attr.LevelUpTable> _dataMap;
    private readonly List<attr.LevelUpTable> _dataList;
    
    public LevelUpTables(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, attr.LevelUpTable>();
        _dataList = new List<attr.LevelUpTable>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            attr.LevelUpTable _v;
            _v = attr.LevelUpTable.DeserializeLevelUpTable(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, attr.LevelUpTable> DataMap => _dataMap;
    public List<attr.LevelUpTable> DataList => _dataList;

    public attr.LevelUpTable GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public attr.LevelUpTable Get(int key) => _dataMap[key];
    public attr.LevelUpTable this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}