//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.skill
{
    /// <summary>
    /// 技能属性
    /// </summary>
    public enum AtkAttribute
    {
        /// <summary>
        /// 为了某些设置部分需要填写全部属性
        /// </summary>
        All = 0,
        /// <summary>
        /// 物理
        /// </summary>
        Physical = 1,
        /// <summary>
        /// 魔法
        /// </summary>
        Magic = 2,
        /// <summary>
        /// 火属性
        /// </summary>
        Fire = 3,
        /// <summary>
        /// 冰属性
        /// </summary>
        Ice = 4,
        /// <summary>
        /// 电属性
        /// </summary>
        Electricity = 5,
        /// <summary>
        /// 光属性
        /// </summary>
        Light = 6,
        /// <summary>
        /// 暗属性
        /// </summary>
        Dark = 7,
        /// <summary>
        /// 毒属性
        /// </summary>
        Poison = 8,
        /// <summary>
        /// 无属性
        /// </summary>
        None = 9,
    }
}
