//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.skill
{
    /// <summary>
    /// 技能附加效果类型
    /// </summary>
    public enum AttachEffectType
    {
        /// <summary>
        /// 技能附加伤害效果
        /// </summary>
        Harm = 1,
        /// <summary>
        /// 技能附加治疗效果
        /// </summary>
        Heal = 2,
    }
}
