//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.skill
{
    /// <summary>
    /// 技能附加效果目标
    /// </summary>
    public enum AttachEffectTarget
    {
        /// <summary>
        /// 占位用
        /// </summary>
        None = 0,
        /// <summary>
        /// 自身
        /// </summary>
        Self = 1,
        /// <summary>
        /// 目标
        /// </summary>
        Target = 2,
    }
}
