//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.skill
{

/// <summary>
/// 技能移动动作配置
/// </summary>
public sealed partial class MoveAction :  Bright.Config.BeanBase 
{
    public MoveAction(ByteBuf _buf) 
    {
        MoveMethod = (skill.MoveMethod)_buf.ReadInt();
        MovePosition = (skill.MovePosition)_buf.ReadInt();
        AttachVfx = _buf.ReadInt();
        PostInit();
    }

    public static MoveAction DeserializeMoveAction(ByteBuf _buf)
    {
        return new skill.MoveAction(_buf);
    }

    /// <summary>
    /// 移动方式
    /// </summary>
    public skill.MoveMethod MoveMethod { get; private set; }
    /// <summary>
    /// 移动位置
    /// </summary>
    public skill.MovePosition MovePosition { get; private set; }
    /// <summary>
    /// 伴随特效
    /// </summary>
    public int AttachVfx { get; private set; }
    public battle.VFXData AttachVfx_Ref { get; private set; }

    public const int __ID__ = 528222532;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        this.AttachVfx_Ref = (_tables["battle.VFXDatas"] as battle.VFXDatas).GetOrDefault(AttachVfx);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "MoveMethod:" + MoveMethod + ","
        + "MovePosition:" + MovePosition + ","
        + "AttachVfx:" + AttachVfx + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
