//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.skill
{
    /// <summary>
    /// 技能移动位置
    /// </summary>
    public enum MovePosition
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 目标位置
        /// </summary>
        TargetPosition = 1,
        /// <summary>
        /// 目标中心位置
        /// </summary>
        TargetCenter = 2,
    }
}
