//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.skill
{
    /// <summary>
    /// 技能移动方式
    /// </summary>
    public enum MoveMethod
    {
        /// <summary>
        /// 原地不动
        /// </summary>
        Stay = 0,
        /// <summary>
        /// 跑
        /// </summary>
        Run = 1,
        /// <summary>
        /// 闪现
        /// </summary>
        Flash = 2,
        /// <summary>
        /// 跳跃
        /// </summary>
        Jump = 3,
    }
}
