//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.skill
{
    /// <summary>
    /// 投射物类型
    /// </summary>
    public enum ProjectileType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 从施法者位置发射向目标位置，多个目标会发射多个子弹
        /// </summary>
        Single_Bullet = 1,
        /// <summary>
        /// 直接在目标位置播放的特效，多个目标会播放多个特效
        /// </summary>
        Single_Target = 2,
        /// <summary>
        /// 从施法者头顶位置发射向目标，到达后造成伤害，多个目标会依次发射召唤物
        /// </summary>
        Single_Summon = 3,
        /// <summary>
        /// 从施法者位置发射向目标位置，多个目标会发射多个炸弹，炸弹轨迹为抛物线
        /// </summary>
        Single_Bomb = 4,
        /// <summary>
        /// 直接在目标阵型中心位置播放特效，多个目标持续受到伤害
        /// </summary>
        Multi_Target = 5,
        /// <summary>
        /// 从施法者头顶位置发射向目标阵型中心位，到达后产生爆炸，命中特效 为爆炸特效，各单位的命中特效使用 技能中设定的 命中特效
        /// </summary>
        Multi_Summon = 6,
        /// <summary>
        /// 从源位置发射向目标阵型中心位，到达后产生爆炸，命中特效 为爆炸特效，各单位的命中特效使用 技能中设定的 命中特效，炸弹轨迹为抛物线
        /// </summary>
        Multi_Bomb = 7,
        /// <summary>
        /// 一般用于近战群体攻击，从施法者位置，面向目标中心位置施放特效
        /// </summary>
        Shockwave = 8,
        /// <summary>
        /// 从原位置向目标中心位置发射，经过目标时产生击中效果，投射物最终会飞出屏幕
        /// </summary>
        Across = 9,
    }
}
