//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.skill
{
    /// <summary>
    /// 技能范围
    /// </summary>
    public enum SkillScope
    {
        /// <summary>
        /// 单体
        /// </summary>
        Single = 1,
        /// <summary>
        /// 全体
        /// </summary>
        All = 2,
    }
}
