//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.skill
{

/// <summary>
/// 技能起始动作配置
/// </summary>
public sealed partial class StartAction :  Bright.Config.BeanBase 
{
    public StartAction(ByteBuf _buf) 
    {
        ActionName = (skill.UnitAnimationNames)_buf.ReadInt();
        ActionDuration = _buf.ReadFloat();
        AttachVfx = _buf.ReadInt();
        PostInit();
    }

    public static StartAction DeserializeStartAction(ByteBuf _buf)
    {
        return new skill.StartAction(_buf);
    }

    /// <summary>
    /// 起始动作名称
    /// </summary>
    public skill.UnitAnimationNames ActionName { get; private set; }
    /// <summary>
    /// 起始动作时长
    /// </summary>
    public float ActionDuration { get; private set; }
    /// <summary>
    /// 伴随特效
    /// </summary>
    public int AttachVfx { get; private set; }
    public battle.VFXData AttachVfx_Ref { get; private set; }

    public const int __ID__ = 2123437307;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        this.AttachVfx_Ref = (_tables["battle.VFXDatas"] as battle.VFXDatas).GetOrDefault(AttachVfx);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ActionName:" + ActionName + ","
        + "ActionDuration:" + ActionDuration + ","
        + "AttachVfx:" + AttachVfx + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
