//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.common
{
    /// <summary>
    /// 攻击属性
    /// </summary>
    public enum AtkProperty
    {
        /// <summary>
        /// 物理攻击
        /// </summary>
        Strength = 1,
        /// <summary>
        /// 魔法攻击
        /// </summary>
        Magic = 2,
    }
}
