//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.common
{

public sealed partial class AudioCatalog :  Bright.Config.BeanBase 
{
    public AudioCatalog(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Priority = _buf.ReadInt();
        DecreasePercent = _buf.ReadFloat();
        PostInit();
    }

    public static AudioCatalog DeserializeAudioCatalog(ByteBuf _buf)
    {
        return new common.AudioCatalog(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 分类名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 说明
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 分类优先级，优先极高的音频播放时，会压低优先权低的音效，相同优先级的音效互不影响
    /// </summary>
    public int Priority { get; private set; }
    /// <summary>
    /// 当有高优先级音频播放时，当前分类音效的衰减百分比<br/>取值 0 - 1
    /// </summary>
    public float DecreasePercent { get; private set; }

    public const int __ID__ = -756315482;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Priority:" + Priority + ","
        + "DecreasePercent:" + DecreasePercent + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
