//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.common
{
    /// <summary>
    /// Npc阵营
    /// </summary>
    public enum Camp
    {
        /// <summary>
        /// Npc阵营，默认对玩家有好
        /// </summary>
        Npc = 1,
        /// <summary>
        /// 怪物阵营，默认对玩家敌对
        /// </summary>
        Monster = 2,
    }
}
