//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.common
{
   
/// <summary>
/// 怪物类型(系)
/// </summary>
public partial class MonsterTypes
{
    private readonly Dictionary<int, common.MonsterType> _dataMap;
    private readonly List<common.MonsterType> _dataList;
    
    public MonsterTypes(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, common.MonsterType>();
        _dataList = new List<common.MonsterType>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            common.MonsterType _v;
            _v = common.MonsterType.DeserializeMonsterType(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, common.MonsterType> DataMap => _dataMap;
    public List<common.MonsterType> DataList => _dataList;

    public common.MonsterType GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public common.MonsterType Get(int key) => _dataMap[key];
    public common.MonsterType this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}