//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.common
{
    /// <summary>
    /// Npc攻击模式
    /// </summary>
    public enum NpcAttackMode
    {
        /// <summary>
        /// 被动攻击，玩家接触以后触发战斗
        /// </summary>
        Passive = 1,
        /// <summary>
        /// 主动攻击，指定范围内有玩家则追击
        /// </summary>
        Positive = 2,
    }
}
