//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.common
{
    /// <summary>
    /// Npc行为
    /// </summary>
    public enum NpcBehaviour
    {
        /// <summary>
        /// Npc在原地站岗，不走动
        /// </summary>
        Guard = 1,
        /// <summary>
        /// Npc在两点之间巡逻
        /// </summary>
        Partol = 2,
        /// <summary>
        /// Npc在指定半径内随机移动
        /// </summary>
        Random = 3,
    }
}
