//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.common
{
    /// <summary>
    /// 投射物体行进路径
    /// </summary>
    public enum ProjectilePath
    {
        /// <summary>
        /// 直线
        /// </summary>
        Straight = 1,
        /// <summary>
        /// 抛物线
        /// </summary>
        Parabola = 2,
    }
}
