//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.common
{
    public enum Quality
    {
        /// <summary>
        /// 白色品质
        /// </summary>
        WHITE = 0,
        /// <summary>
        /// 绿色品质
        /// </summary>
        GREEN = 1,
        /// <summary>
        /// 蓝色品质
        /// </summary>
        BLUE = 2,
        /// <summary>
        /// 紫色品质
        /// </summary>
        PURPLE = 3,
        /// <summary>
        /// 橙色品质
        /// </summary>
        Orange = 4,
        /// <summary>
        /// 红色品质
        /// </summary>
        Red = 5,
    }
}
