//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.common
{
    /// <summary>
    /// 抗性的数值范围
    /// </summary>
    public enum ResistanceRange
    {
        /// <summary>
        /// 抗性的起始id = ResiFire
        /// </summary>
        Start = 1,
        /// <summary>
        /// 抗性的结束id = ResiFrozen
        /// </summary>
        End = 10,
    }
}
