//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.common
{
    /// <summary>
    /// 特效类型
    /// </summary>
    public enum VfxType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 技能命中特效
        /// </summary>
        HitVfx = 1,
        /// <summary>
        /// 技能伴随特效
        /// </summary>
        AttachVfx = 2,
        /// <summary>
        /// 技能群体特效
        /// </summary>
        GlobalVfx = 3,
        /// <summary>
        /// 投射物特效
        /// </summary>
        ProjectileVfx = 4,
        /// <summary>
        /// 投射物发射特效
        /// </summary>
        MuzzleFlash = 5,
    }
}
