//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.avatar
{

public sealed partial class AvatarHeadData :  Bright.Config.BeanBase 
{
    public AvatarHeadData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ObjectName = _buf.ReadString();
        AllowHeadWear = _buf.ReadBool();
        CreateActor = _buf.ReadBool();
        PostInit();
    }

    public static AvatarHeadData DeserializeAvatarHeadData(ByteBuf _buf)
    {
        return new avatar.AvatarHeadData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// GameObject名称
    /// </summary>
    public string ObjectName { get; private set; }
    /// <summary>
    /// 是否允许佩戴头饰
    /// </summary>
    public bool AllowHeadWear { get; private set; }
    /// <summary>
    /// 是否开放给玩家创建角色使用
    /// </summary>
    public bool CreateActor { get; private set; }

    public const int __ID__ = -1237638280;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ObjectName:" + ObjectName + ","
        + "AllowHeadWear:" + AllowHeadWear + ","
        + "CreateActor:" + CreateActor + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
