//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.avatar
{

public sealed partial class AvatarSenseData :  Bright.Config.BeanBase 
{
    public AvatarSenseData(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        PartId = _buf.ReadInt();
        Part = (avatar.HeadWearType)_buf.ReadInt();
        ObjectName = _buf.ReadString();
        CreateActor = _buf.ReadBool();
        PostInit();
    }

    public static AvatarSenseData DeserializeAvatarSenseData(ByteBuf _buf)
    {
        return new avatar.AvatarSenseData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 部位Id
    /// </summary>
    public int PartId { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public avatar.HeadWearType Part { get; private set; }
    /// <summary>
    /// GameObject名称
    /// </summary>
    public string ObjectName { get; private set; }
    /// <summary>
    /// 是否开放给玩家创建角色使用
    /// </summary>
    public bool CreateActor { get; private set; }

    public const int __ID__ = 992434282;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "PartId:" + PartId + ","
        + "Part:" + Part + ","
        + "ObjectName:" + ObjectName + ","
        + "CreateActor:" + CreateActor + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
