//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.avatar
{
   
/// <summary>
/// Avatar身体配置数据
/// </summary>
public partial class AvatarBodyDatas
{
    private readonly Dictionary<int, avatar.AvatarBodyData> _dataMap;
    private readonly List<avatar.AvatarBodyData> _dataList;
    
    public AvatarBodyDatas(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, avatar.AvatarBodyData>();
        _dataList = new List<avatar.AvatarBodyData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            avatar.AvatarBodyData _v;
            _v = avatar.AvatarBodyData.DeserializeAvatarBodyData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, avatar.AvatarBodyData> DataMap => _dataMap;
    public List<avatar.AvatarBodyData> DataList => _dataList;

    public avatar.AvatarBodyData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public avatar.AvatarBodyData Get(int key) => _dataMap[key];
    public avatar.AvatarBodyData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}